### ISSUE TITLE
Make size of direction component arrows configurable

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#102]
The direction component sets style properties like translation in code. Therefor it is not possible to change the style only by overriding the CSS. This causes problems when the navigation arrows become too small.

The style component should be configurable so that the navigation arrows can be resized arbitrarily.

**Comment by gyllen** [comment]
Is it also possible to replace the arrows, in the latest designs from @angelday we need to replace the arrows of center when different elements are pulled in from the side.
