### ISSUE TITLE
Add ability to read and set pan and tilt in Pano

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#103]

**Comment by oscarlorentzon** [comment]
When bearing can be set it is natural to have the ability to set the pitch too. Both properties should be included in this issue.

**Comment by oscarlorentzon** [comment]
The API for setting the pan, tilt and zoom should be `x`, `y`, `z` where `x` and `y` are the basic coordinates and `z` is the zoom level.

**Comment by oscarlorentzon** [comment]
This issue should include setting pan, tilt and zoom in perspective images too (in any image actually). The API should be the same.

**Comment by oscarlorentzon** [comment]
All mentions of phi and theta should be changed to pan and tilt with the implementation of this issue.
