### ISSUE TITLE
Define design and interaction for the tag component

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#105]
The tag component needs design for showing detection rectangles and their metadata for different purposes. To start with:
- [ ] Traffic signs
- [ ] Blurs
- [ ] OCR

All classes of detections need to have a common design and a defined interaction behavior for the following:
- [ ] Resize
- [ ] Move
- [ ] Remove detection
- [ ] Add new detection

Interaction behavior should handle very small rectangles in a good way.

**Comment by todrobbins** [comment]
[Fabulous work so far!](http://blog.mapillary.com/update/2016/05/19/mapillary-js-tagging.html) One minor UI suggestion: when you click on the `Create bounding box` or `Create point` buttons, etc., it would be great if the cursor (on desktop) changed to reflect the action by utilizing the CSS `cursor` property types. So for your suggested classes above, perhaps:

## Resize
```
cursor: n-resize;
cursor: e-resize;
cursor: s-resize;
cursor: w-resize;
cursor: ns-resize;
cursor: ew-resize;
cursor: ne-resize;
cursor: nw-resize;
cursor: se-resize;
cursor: sw-resize;
cursor: nesw-resize;
cursor: nwse-resize;
```
## Move
`cursor: move;`
## Remove detection
`cursor: pointer;`?
## Add new detection
`cursor: crosshair;`

Thoughts?

**Comment by oscarlorentzon** [comment]
@todrobbins Thanks for the suggestions.

Agree that different cursors for different actions would help by making it clearer when something can be done and what can then be done. We will add some more geometries and improve the cursor behavior for the complete functionality. 

Your suggestions for move, remove and seems very natural indeed. Resizing bounding boxes in the corners is unrestricted right now so we need to ensure that the potential resize arrows does not indicate something that is more restricted than what you actually can do.

**Comment by oscarlorentzon** [comment]
Cursors where implemented according to above suggestions in [1.6.0](https://github.com/mapillary/mapillary-js/releases/tag/v1.6.0) which is live on [mapillary.com](https://www.mapillary.com) and can be seen in blur editing mode.

**Comment by todrobbins** [comment]
@oscarlorentzon fabulous! It looks great. I think this will be really helpful.

**Comment by oscarlorentzon** [comment]
Closing in favor of creating more specific issues for future changes of/additions to the tag design/behavior.
