### ISSUE TITLE
Improve node class implementation, document and include in docs

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#110]
The node class is exposed in the `nodechanged` event but is not in the documentation. The node class should be documented and before that the properties should be changed to readonly.

**Comment by oscarlorentzon** [comment]
When exposing the `Node` class in the docs we also need to expose the `ILatLon` interface there. Before doing that we need to decide on a naming for the `latitude` `longitude` interface (see #111).

**Comment by oscarlorentzon** [comment]
All properties in the node class should not be exposed in the docs. This could be handled by documenting an interface and let the node class implement it.

**Comment by tomwayson** [comment]
I'm particularly interested in the heading (compass direction) that the photo was taken at. I think this might be the `ca` property?

I'm also interested in any indication of any measure of how close the returned image is to the input lat/lon specicifed in the call to `moveCloseTo`. Possibly the `worthy` property?

**Comment by oscarlorentzon** [comment]
Yes, heading is in the `ca` (compass angle) property.

Worthy indicates whether all surrounding tiles needed for a node to be able to calculate its edges in all directions have been retrieved or not. 

There is currently no public API method/property for getting the measure of how close the input lat/lon of `moveCloseTo` is to the node lat/lon. There is a class in the library for doing this calculation though but it is not exposed: https://github.com/mapillary/mapillary-js/blob/master/src/geo/GeoCoords.ts
