### ISSUE TITLE
Rename LatLon to LngLat

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#111]
Rename all occurrences of latLon to lngLat and all occurences of lon to lng.

**Comment by oscarlorentzon** [comment]
@gyllen The API returns responses with properties named lon, e.g. APINavImIm and APISearchImClose2 which would cause mixed `lon` and `lng` naming in the library as long as the API does not change.

`latlon-geohash` also uses the `latLon` convention so for clarity it should always be converted to a `lngLat` before being sent as a parameter or used for calculations.

**Comment by gyllen** [comment]
@oscarlorentzon Do you need any action from me here?

**Comment by oscarlorentzon** [comment]
When changing the naming the for the parameters of all methods taking `longitude` and `latitude` should be changed from `(lat, lon)` to `(lng, lat)` to make everything unified. 

The viewer has the `moveCloseTo(lat, lon)` API method which should then be changed to `moveCloseTo(lng, lat)` when making this change. That is a breaking API change.

**Comment by gyllen** [comment]
So we have to push Mapillary to 2.0.0 after this change then?

**Comment by oscarlorentzon** [comment]
Should be unified across libraries/APIs if done. Right now the code in `mapillary-js` would be mixing lon and lng in the code which is confusing. Postponing and closing for now. New issue to be opened if a cross library change is to be implemented in the future.
