### ISSUE TITLE
Smoother load of first image

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#118]
If cover is not activated load image smoother. The chrome plugin loads the first image in a very nice way.

**Comment by oscarlorentzon** [comment]
Need some more information here to be able to understand the desired behavior.

What part of the chain should load the image smoother? Should the cover component load the image smoother? Should the GL rendering shown after the cover component is hidden load the image smoother?

The chrome plugin fades in the opacity of the image. Is that what you mean by loading the first image smoother?

If the desired behavior relates to the cover component, why should it only be `smooth` when the cover is not activated?

**Comment by gyllen** [comment]
We should work with @angelday to redo the transistions from nothing -> cover -> full viewer. The way we handle this now feels quite "clunky".

**Comment by oscarlorentzon** [comment]
There are also other cases, like in the phone apps where the viewer sometimes need to be deactivated and activated when the viewer goes out of view. In those cases you really do not want any additional UI elements, loading indicators or fade in fade out at all, just a simple image overlay.

**Comment by gyllen** [comment]
True, are you guys looping in @angelday on this subject?

**Comment by oscarlorentzon** [comment]
@gyllen Do you consider this issue resolved with the implementation of #180 or do you want to change it further?
