### ISSUE TITLE
Restyle navigation arrows 

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#121]
The navigation arrows should be restyled according to the design of @angelday from #96.

![screen shot 2016-05-04 at 15 25 53](https://cloud.githubusercontent.com/assets/50189/15015492/8237de84-120c-11e6-82f4-767e95b47dbf.png)

**Comment by oscarlorentzon** [comment]
@angelday Can you verify that this is the final design for the navigation arrows (for now)?

**Comment by gyllen** [comment]
I think we need to think a little bit about how to place both the play, skip buttons (this is where we have the searchbar today in elva) and also not put the right/left/turn all the way to the sides. That will not look great in fullscreen.

**Comment by oscarlorentzon** [comment]
A note: The library user will be able to change the position of the `Sequence/Play` element by overriding the CSS of the class for that element.

**Comment by gyllen** [comment]
Synch with @angelday preferably post final design in this issue.

**Comment by oscarlorentzon** [comment]
Is there an indication of some sort when hovering the navigation arrows in this design? 

Is the opacity of the chevrons always 1?

**Comment by angelday** [comment]
Discussed. For JS we like this layout and also the fact that seq. steppers are not linked with spatial.

To answer the question: opacity is always 1, but on hover we'll be changing the ovals color to a darker tone, most probably by shifting the opacity, eg. from 0.6 to .75

**Comment by angelday** [comment]
The spatial arrows as SVG's:

![screen shot 2016-05-26 at 15 07 06](https://cloud.githubusercontent.com/assets/50189/15575511/91d4884e-2353-11e6-97ae-e3e2e655bf06.png)

[arrows.svg.zip](https://github.com/mapillary/mapillary-js/files/284400/arrows.svg.zip)

We'll tweak the hover states etc. in code.
