### ISSUE TITLE
FPS calculation faulty after cover deactivation

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#125]
The first FPS calculation in the state is incorrect because the initial value of the time is taken when the `StateService` is constructed, not when it is started. This causes the first transition after cover deactivation to be very fast if one navigates immediately after the cover component has been deactivated. This happens for every deactivation.

The FPS observable should set the initial time value correctly every time the `StateService` is started.

**Comment by gyllen** [comment]
Good catch @oscarlorentzon
