### ISSUE TITLE
Provide mapillary-js builds without external libraries (e.g. RxJS)

### ISSUE THREAD

**Issue by knikel** [mapillary/mapillary-js#132]
When used on future mapillary.com we'll be importing RxJS twice, we should provide leaner builds of `mapillary-js` and assume users will have the required libraries available. This will be especially useful when we update to RxJS 5, only import used operators and shake off the unused code -- both here an in mapillary.com.

**Comment by gyllen** [comment]
How big is RxJS, also can we use leaner versions of RxJS and just combine functions?

**Comment by oscarlorentzon** [comment]
Related to #117

**Comment by oscarlorentzon** [comment]
Related to #87

**Comment by knikel** [comment]
Closing since irrelevant
