### ISSUE TITLE
Resource not found when using mapillaryJS

### ISSUE THREAD

**Issue by kepta** [mapillary/mapillary-js#133]
I am running into this error 
```
Graph.ts:73 Uncaught TypeError: Cannot read property '0' of undefinedt.addNodesFromAPI @ Graph.ts:73(anonymous function)

```

So, after inspecting further 
This API fails https://a.mapillary.com/v2/nav/im/VHU9_wcTMUlpNe6xyoY8PQ?client_id=NzNRM2otQkR2SHJzaXJmNmdQWVQ0dzo1ZWYyMmYwNjdmNDdlNmVi

Working example over [here](http://kushanjoshi.com/mapillary_test/k.html). 
As you can see the cover image is loaded. But the moment I click, an uncaught error is thrown.

Any help would be really appreciated, as I am integrating mapillaryJS to iD editor for OpenStreetMap.

cc @gyllen

**Comment by oscarlorentzon** [comment]
Thanks for reporting.

There are two problems. The server responds with 404 for the tile request for this particular image and we do handle this in `mapillary-js`. Will look into both problems.

**Comment by kepta** [comment]
@oscarlorentzon it would be awesome if mapillary-js could catch such errors.

**Comment by peterneubauer** [comment]
That's a lag in the system, the image is only a few hours old, we are working on it. Try something a bit older. like https://a.mapillary.com/v2/nav/im/1gE6B94DP0iDmUHjtRFKcQ?client_id=NzNRM2otQkR2SHJzaXJmNmdQWVQ0dzo1ZWYyMmYwNjdmNDdlNmVi

**Comment by kepta** [comment]
@peterneubauer could you also update on error handling of these kind of error by mapillary-js?

**Comment by peterneubauer** [comment]
Good idea! BTW the first api link is working now.

**Comment by gyllen** [comment]
@kepta We will update error handling accordingly

Please note that this is not common practice though. This was caused by some internal database shard reallocations.

**Comment by oscarlorentzon** [comment]
MapillaryJS now handles errors gracefully. When IO errors occur for navigation through components (navigation arrows) the errors will be logged. When IO errors occur for calls to `Viewer.move*` methods the errors will propagate to the caller who needs to catch the errors.

https://github.com/mapillary/mapillary-js/blob/3a0ab4777df0aac8ba3204583d034927fce98515/MIGRATING.md
