### ISSUE TITLE
accessing 3D image orientation

### ISSUE THREAD

**Issue by mbredif** [mapillary/mapillary-js#137]
The current API seems to provide only 2D orientations through (3 DOF: lat,lon,ca). Are 3D orientations available with their 6 degrees of freedom :  position (x,y,z or lat,lon,altitude) and 3D rotation (eg roll, pitch,yaw) ?

**Comment by oscarlorentzon** [comment]
Currently the API exposes the latitude, longitude and compass angle on the node class which can be retrieved through the `nodechanged` event on the viewer class. 

1. Are you using the `nodechanged` event to get the 3DoF?

The node also exposes the `node.apiNavImIm.rotation` (angle axis representation) and `node.apiNavImIm.orientation` properties which contains all the information needed to get the 6DoF. This is not documented at this point and the library has helper classes doing calculations internally based on those two properties.

Internally the library creates a `transform` class instance and a `camera` class instance for every node that is navigated to. The transform instance is used for coordinate transformations. The `camera` instance is used for determining the 3D orientation of the node and for interpolating the position of the render camera. 

The `camera` instance defines the `position`, `lookat` and `up` vectors of the node in a local topocentric East, North, Up reference frame as well as the `focal length`. These properties play well with the `three-js` perspective camera used for rendering. We do not expose this information through the API currently. 

See the https://github.com/mapillary/mapillary-js/tree/master/src/geo folder for a reference on the classes.

2. Are you developing a component or an integration?

3. How often do you need the 3D orientation? For each frame or for each new node only?

**Comment by oscarlorentzon** [comment]
Closing discussion because of lack of activity. 

Happy to reopen if there are more questions or actual feature requests.

**Comment by vpicavet** [comment]
Hi,
I had an opportunity to talk with Peter Neubauer at FOSS4G. He said the full position + orientation ( roll, pitch, yaw) should be known from the sparse reconstruction.
What we would like would be to have this information in the REST API.
The aim is to support mapillary as a source for projective texturing in iTowns 2 ( www.itowns-project.org ). We need the 3D orientation for each frame.

**Comment by oscarlorentzon** [comment]
@vpicavet We do not currently have a supported REST API for accessing this information. What we have available at the moment for an image are the properties listed here https://a.mapillary.com/#images-im. We are working on a new version of the REST API where we aim to provide the information you mention along with documentation on how to access it. 

Interesting project by the way and thanks for your patience.

**Comment by vpicavet** [comment]
ok, thanks for the information. We will be patient and wait for the new API :-)
