### ISSUE TITLE
Handle unworthy nodes

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#14]
Unworthy nodes should be created at the edges of tiles. When navigating to the unworthy nodes the surrounding tiles should be fetched and the edges for the unworthy nodes should be recalculated.

**Comment by oscarlorentzon** [comment]
This should also handle edges to sequence nodes that are outside of any of the previously cached tiles.

**Comment by gyllen** [comment]
Worthy logic is impemented, whats neeed now is a proper implementation of Spatial.worthyHs (feel free to rename :))
