### ISSUE TITLE
Sequence Not Renedered on Mapillary Map

### ISSUE THREAD

**Issue by PaulColinSimpson** [mapillary/mapillary-js#140]
There is a sequence I recorded and uploaded to the Mapillary server (User: Essex_boy) at location N51.64276 E0.03465 on the A104 Epping new road. This however is not rendered in green on the map but the sequence is available to view if you select this part of the road.

**Comment by knikel** [comment]
@PaulColinSimpson: I'm moving this issue to mapillary_issue, which is a general tracker for all Mapillary issues, this repository is for tracking all issues that relate to `mapillary-js`, the viewer library.
