### ISSUE TITLE
moveCloseTo method not working ?

### ISSUE THREAD

**Issue by mdouchin** [mapillary/mapillary-js#147]
Hi,

I tried to the use method moveCloseTo in a very quick&dirty copy/paste from documentation

```
var mly = new Mapillary.Viewer('mly', 'cjJ1SUtVOEMtdy11b21JM0tyYTZIQTo2ZmVjNTQ3YWQ0OWI2Yjgx', 'ytfE1_iD_N-jmHfTHkj1Ug');
mly.moveCloseTo(43.61105, 3.87282);
```
I got no erros in Firefox dev tools. I have a successfull call to the image : 

https://d1cuyjsrcm0gby.cloudfront.net/wS-P6an2s8C9gnrpq85kgw/thumb-640.jpg?origin=mapillary.webgl

then some other requests like
https://a.mapillary.com/v2/nav/h/u09tuny?client_id=cjJ1SUtVOEMtdy11b21JM0tyYTZIQTo2ZmVjNTQ3YWQ0OWI2Yjgx

but the view is not refreshed

I tried it on the example, but it did not work either: http://bl.ocks.org/peterneubauer/5870cbab81221503fb0c

Am I missing something here ?

**Comment by oscarlorentzon** [comment]
When the cover is activated it is not possible to move to nodes by any of the `move` methods on the `Viewer` class. You should be able to make it work by doing:

```
var mly = new Mapillary.Viewer(
   'mly', 
   'cjJ1SUtVOEMtdy11b21JM0tyYTZIQTo2ZmVjNTQ3YWQ0OWI2Yjgx', 
   'ytfE1_iD_N-jmHfTHkj1Ug',
   { cover: false }
);
mly.moveCloseTo(43.61105, 3.87282);
```

This immediately deactivates the cover. You will then first move to the initial key specified in the Viewer constructor though.

Another way to do it is to initialize the viewer without a key if you really want to make the close to call directly: 

```
var mly = new Mapillary.Viewer(
   'mly', 
   'cjJ1SUtVOEMtdy11b21JM0tyYTZIQTo2ZmVjNTQ3YWQ0OWI2Yjgx', 
   null,
   { cover: false }
);
mly.moveCloseTo(43.61105, 3.87282);
```

It is more natural not to make a `move` call immediately after creating the viewer instance though. Instead create the viewer (with or without a key), deactivate the cover and use `moveCloseTo` after a click on a map or similar.

Hope that helps.

**Comment by mdouchin** [comment]
Thanks a lot, that helped !
It is indeed more natural not to make this call. I just tried to build a quick way to check this method, before integrating it deeper in https://github.com/3liz/lizmap-web-client 


For thoses interested, here is the proper doc about:

* cover option: https://mapillary.github.io/mapillary-js/interfaces/ivieweroptions.html#cover
* moveCloseTo: https://mapillary.github.io/mapillary-js/classes/viewer.html#movecloseto

**Comment by oscarlorentzon** [comment]
Cool! Thanks for providing the doc links.
