### ISSUE TITLE
Prefix all mapillary-js CSS classes to prevent CSS bleed

### ISSUE THREAD

**Issue by knikel** [mapillary/mapillary-js#149]
While trying to use `1.4.1` in **iD editor** CSS gets cross polluted (mainly `.icon` class is to blame). I prefixing all commonly sounding (e.g. `.button`, `.btn`, etc.) classes with for examply `.mly-*` could be a solution. Another one is to scope all our classes under `.mapillary-js`. Thoughts, @oscarlorentzon?

**Comment by oscarlorentzon** [comment]
Is there a good argument for using commonly named classes?

I think we should prefix every CSS class used throughout the library with `mapillary-js`, `mapillaryjs`, `mapillary` or `mly`. Then the components should also prefix with component name after the `mapillary` prefix to distinguish component CSS classes.

We should also use a common naming convention for all the CSS classes. All lowercase with hyphens?

**Comment by knikel** [comment]
@oscarlorentzon: The argument is they are easy to comprehend and descriptive. `.icon` means I'm styling an icon.

I went through whole CSS I think I don't see a point of prefixing all the classes with `mly-*`. Then main _offender_ that could cause some issues with integrations is really `.icon` class. Renaming it to `.SequenceComponentIcon` will solve it. Besides that we are using pascal case for naming CSS classes, that itself already reduces integration issues. It just happens that *iD* has a clash with one of our classes. Other than that I think we're safe really.
