### ISSUE TITLE
Panorama indicator not shown for panoramas

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#153]
**mapillary-js version**: 1.4.1

### Steps to Reproduce Behavior

 1. Navigate to a panorama.

### Expected Behavior

Panorama indicator is shown.

### Actual Behavior

No panorama indicator is shown.

Introduced in deb05e10a0970898a04da4ead9b67c77f13a8788.

**Comment by oscarlorentzon** [comment]
An improved version of the panorama indicator could show the direction with respect to north for the current viewing direction.

The viewer should also change the cursor to `grab` when it is possible to grab and look around. Needs to be prioritized between other components like the `tag` to ensure that the correct cursor is shown in all situations.

**Comment by angelday** [comment]
Reference:

![screen shot 2016-06-22 at 17 03 04](https://cloud.githubusercontent.com/assets/50189/16271739/75f00b28-389b-11e6-9c0c-57e8ce8fdff9.png)

Pano marker is located bottom right. The size should be 28x28 px.

[pano_indicator.svg.zip](https://github.com/mapillary/mapillary-js/files/328170/pano_indicator.svg.zip)
