### ISSUE TITLE
Detection component should not request detections

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#154]
**mapillary-js version**: 1.4.1

### Steps to Reproduce Behavior

 1. Enable the direction component

### Expected Behavior

Nothing should happen unless the library user provides rectangles to the detection component.

### Actual Behavior

Detection component is making requests for rectangles from the APIv3. 

A side effect of the requests is that Mixed content errors occur if the site using the library is served over HTTPS because the URL to the vector tiles service is made over HTTP.

Discovered here: esridc/ember-cli-mapillary#3

**Comment by oscarlorentzon** [comment]
@gyllen 

1. Should this https://github.com/mapillary/mapillary-js/blob/master/src/utils/Urls.ts#L7 be removed when moving to new tile API?
2. Should all the URL:s be HTTPS?

**Comment by gyllen** [comment]
@oscarlorentzon Yes, we will setup the proxy so you will call https://a.mapillary.com/v3/XXX still working on that though. But yes ALL urls has to be https.
