### ISSUE TITLE
Add LookAt API

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#156]
Add `lookAt(lon, lat)`

This will open up MapillaryJS giving the image that best matches a view of the lon,lat

**Comment by Neurostep** [comment]
Hi all,

I am just trying to dive into the `mapillary-js` to get more practice with TypeScript and related technologies. To do this, I've decided to try to close this issue =)

Discovering the API and public examples I have found that `lookAt` semantics is very similar to [moveCloseTo](https://mapillary.github.io/mapillary-js/classes/viewer.html#movecloseto) one. Could anybody provide me some info what the main difference between these two methods? Or may somebody give more examples and semantics description of the proposed `lookAt` method?

Thanks

**Comment by gyllen** [comment]
@Neurostep I would say the only difference is that close to tries to get an image as close to the coordinate i.e. a click on a map. The lookAt should use a Mapillary API so that it tries to get an image that actually is looking at the coordinate that you are providing, Does that make sense?

**Comment by Neurostep** [comment]
@gyllen yeah, make sense. Thanks for clarification, will do the PR

**Comment by oscarlorentzon** [comment]
A `LookAt` wrapper will not be added to MapillaryJS. The API should be used instead.
