### ISSUE TITLE
Regular photos not shown on Linux x86_64 Firefox 43.0

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#164]
Originally reported by @simonmikkelsen here: mapillary/mapillary_issues#2026

**Platform:** Web: Mozilla/5.0 (X11; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0

**MapillaryJS version:** 1.5.0
### Steps to reproduce behavior

Go to any normal image like https://www.mapillary.com/app/user/tryl?lat=55.394135&lng=10.186666&z=17&pKey=WAwGFLl7xIWrXMopS_fPeA&focus=photo
### Expected behavior

Observe that instead of the image there is just black. No errors, no warnings. Logo, arrows, minimap, the bar on the right: Everything else but the image is there.
### Actual behavior

Instead of black: An image.
### Additional information

The old site worked perfectly in this browser. I do not have hardware acceleration, but Firefox emulated it quite nice (slower, but nice). Also see the warnings from the dev console on the screenshot. 

Photo spheres works perfectly.

![mapillary-2016-07-21-bug](https://cloud.githubusercontent.com/assets/8446338/17033086/b47d71e4-4f7c-11e6-87d7-e677ccef5a67.png)

**Comment by simonmikkelsen** [comment]
Thanks.
The test build starts by showing the picture, then it fades to black within 1-2 seconds.
On the official Mapillary it only shows the "Loading" spinner, then fades to black after 1-2 seconds. No picture is ever shown.

This is a screenshot of the test build:
![mapillary-js-issues-164-testbuild](https://cloud.githubusercontent.com/assets/8446338/17048695/2e3e59ec-4fe8-11e6-8397-95ac4621b081.png)

**Comment by oscarlorentzon** [comment]
@simonmikkelsen Thanks for testing.

I have made another test build that is available here: https://dl.dropboxusercontent.com/u/40134832/mjs-1.5.1/index.html

Would be great help if you can test that link.

I also just want to ensure that I understand the problem correctly. 

1. When you navigate using the navigation arrows do you see a photo fading in? 
2. Is it shown for approximately 2 seconds?
3. Does the screen become black instantly after 2 seconds (as opposed to fading out)?

**Comment by oscarlorentzon** [comment]
@simonmikkelsen I have created a debug build with extra WebGL logging. 

Can you try this build here and see if you get any logs in the console when your problem happens (you can also change the start key after the hash sign in the URL to try other photos):

Regular photo:

http://mapillaryjs.azurewebsites.net/debug/webgl-debug.html#9Pxb4J3Hn9qYkS_rAhPIGw

Panorama: 

http://mapillaryjs.azurewebsites.net/debug/webgl-debug.html#6qdkvi2qQC627cqi8MUnZA

**Comment by simonmikkelsen** [comment]
On 12/27/2016 04:31 PM, Oscar Lorentzon wrote:

Just tried it: Regular photo: Still just black with working navigation 
controls and everything,
Panorama: Works perfectly.

Both get this in the Javascript console: THREE.WebGLRenderer 831 
mapillary.js:12223:155

Currently I am using a Linux distro with webgl enabled, and this bug is 
no problem to me. But I will gladly assist in finding the cause.

**Comment by oscarlorentzon** [comment]
Thanks for testing. 

I was hoping for error logs from WebGL when the regular images went black. Unfortunately there were none. We have tested the library on different Linux distributions (e.g. Ubuntu) with Firefox and Chrome and have not seen this problem.

Could you give the details regarding both the Linux distributions, the one where it fails and the one where it works? Do you have WebGL disabled in the one where it fails? What browsers are you using? Does it behave the same in all of them.

**Comment by simonmikkelsen** [comment]
It does not work on LMDE Cinnamon Edition with kernel 3.11-2-amd64 from Debian 4.8.1-10.  That kernel is rather old - from 2013. I use the nouvau drivers, which does not support 3D or hardware acceleration. For that reason Firefox uses software rendering. In Chrome (that does not use hardware rendering) Mapillary detects this and displays an error message.

Works in Firefox on Ubuntu 16.04.1 LTS 4.4.0-53-generic with Nvidia drivers. In Chromium (not Chrome) on this distro I get an error message saying that WebGL is not supported. I guess it does not talk with the drivers.

**Comment by oscarlorentzon** [comment]
Thanks for the info. 

Great that it works on Ubuntu 16.04.1.

**Comment by simonmikkelsen** [comment]
After my harddisk broke and I reinstalled my system, I have no longer been able to reproduce the issue. I would just close it.

**Comment by oscarlorentzon** [comment]
That sounds good. Sorry about the harddisk. Thanks for notifying.
