### ISSUE TITLE
Redesign Cover button and animation

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#167]
Its time to upgrade folks.

**Comment by angelday** [comment]
Final design:

![screen shot 2016-07-28 at 14 27 52](https://cloud.githubusercontent.com/assets/50189/17212425/8be0ac9e-54cf-11e6-872d-ac8fbb7b3310.png)

Gradient 180px tall: `background-image: linear-gradient(-180deg, rgba(0,0,0,0.00) 0%, #000000 100%);`

`Explore` button works and looks just like we have it on our front page (note `:hover`)

Logo padding: `30px bottom left`
Button: `30px bottom`
