### ISSUE TITLE
Reimplement Detection component

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#181]
The detection component should not fetch any data and should have an API for setting the rectangles to be shown.

**Comment by gyllen** [comment]
@oscarlorentzon Can't we just use the draw component for this?

**Comment by oscarlorentzon** [comment]
Yes, alternative to reimplementing is to discard the `Detection` component.

**Comment by oscarlorentzon** [comment]
Related to #154

**Comment by gyllen** [comment]
Go for discarding (as discussed on slack)
