### ISSUE TITLE
broken examples b/c no https when loading leaflet CDN over http

### ISSUE THREAD

**Issue by stevenvandervalk** [mapillary/mapillary-js#183]
### Steps to Reproduce Behavior
1. Open https://bl.ocks.org/knikel/151a77df042cd3890502 or another example from https://bl.ocks.org/knikel or https://github.com/mapillary/mapillary-js#examples
2. Notice leaflet doesn't load.
3. Check out console and enjoy the red text.
### Expected Behavior

Load leaflet lib over https
See a lovely leaflet map with MapillaryJS

**Comment by stevenvandervalk** [comment]
After a quick look around I went with https://cdnjs.com/libraries/leaflet since leaflet has https://github.com/Leaflet/Leaflet/issues/1824 ongoing

**Comment by oscarlorentzon** [comment]
Thanks for reporting.

Reverted to HTTP for the examples that failed over HTTPS for now. Should work on [Readme](https://github.com/mapillary/mapillary-js) and [Docs](https://github.com/mapillary/mapillary-js#examples). It is not possible to make pull requests for GitHub gists so we will fix the actual blocks later to be able to change all links to HTTPS and have them working.

Keeping this issue open until we have HTTPS on all examples.
