### ISSUE TITLE
Add an option to `Esc` after clicking to begin a detection box

### ISSUE THREAD

**Issue by todrobbins** [mapillary/mapillary-js#186]
**[mapillary-js 1.6.0](https://github.com/mapillary/mapillary-js/releases/tag/v1.6.0)**:

Adding an option to `Esc` after clicking to begin a detection box would be very handy since having to move the cursor back to the original point and clicking again to clear is a bit tedious.

Thoughts?

**Comment by oscarlorentzon** [comment]
I agree that a shortcut would be handy to abort by a key command such as 'Esc'. We will need to determine if the actual key should be hardcoded in the library or configurable, if it should be turned on by default and so on.

Also we need to define a behavior for other geometries like polygons with respect to the number of already created vertices.

**Comment by oscarlorentzon** [comment]
Functionality for creating and editing tags will not be prioritized going forward.
