### ISSUE TITLE
The street area is black.

### ISSUE THREAD

**Issue by Linomar** [mapillary/mapillary-js#187]
I'm a programmer and I'm using Mapillary-js. The system I've developed is showing a black screen in the area where the street images should appear. It happens in home screen, and even after the command "moveCloseTo" it remains not showing anything, all the area is black.
Could it be a problem with my "client id"?
What is going on?   

**mapillary-js version 1.6**:

link rel="stylesheet" href="https://npmcdn.com/mapillary-js@1.6.0/dist/mapillary-js.min.css" />
script src="https://npmcdn.com/mapillary-js@1.6.0/dist/mapillary-js.min.js"></script>
script type="text/javascript" >
   panorama = new Mapillary.Viewer('street_canvas',
                                   'a1VxV2tOSDYzLUplWDFlVWp6c0lCZzpkZWE4ODJkMzUzODgzOGMy',
                                   null);
                                   //{ cover: false });   // N2MzNjg4MTY1ZDllYjliZGRhZDgzYWEwMjdiN2ZiYjI='); 
   //panorama.moveCloseTo(-30.034627,-51.2132878);

**Comment by oscarlorentzon** [comment]
Thanks for using the library.

Have you followed the steps described in the [README](https://github.com/mapillary/mapillary-js/blob/master/README.md) for creating your client ID and initializing the viewer?

**Comment by Linomar** [comment]
Thanks for answering me.
Putting the photo ID without the argument "cover" it is shown without any problem, but clicking on the button "explore" the image becomes black and this error appears in the console.

> THREE.WebGLRenderer 79                                                  - mapillary-js.min.js:33 
> THREE.WebGLRenderer: ANGLE_instanced_arrays extension not supported.    - mapillary-js.min.js:33 

If I put the argument "cover" and null in the initial photo the screen becomes black, and when I write the command "moveCloseTo" the same error appears in the console, and the screen becomes black.

> THREE.WebGLRenderer 79                                                  - mapillary-js.min.js:33 
> THREE.WebGLRenderer: ANGLE_instanced_arrays extension not supported.    - mapillary-js.min.js:33 
 
In this example [http://bl.ocks.org/knikel/raw/151a77df042cd3890502/](url) the same error is shown in the console, but if I write the command "mly.moveCloseTo (-30.034627, -51.2132878);" no problem is shown.

**Comment by oscarlorentzon** [comment]
These are not errors but information and warning logs. The library does not use the `ANGLE_instanced_arrays` extension so it should work without that. 

Have you followed the steps described in the [README](https://github.com/mapillary/mapillary-js/blob/master/README.md) for creating your client ID and initializing the viewer?

If you can see the viewer [here](http://bl.ocks.org/knikel/151a77df042cd3890502) and the navigation works then your browser should have everything needed for building a web page using the library. Hope that helps.

**Comment by oscarlorentzon** [comment]
@Linomar Did you successfully develop a web page with a MapillaryJS integration?

**Comment by oscarlorentzon** [comment]
Closing with lack of activity. Notify if problem occurs again.
