### ISSUE TITLE
Put a sequence slider in to complement the sequence stepper

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary-js#190]
In order to fast-slide along a sequence and find relevant stops, under the sequence stepper there could be a slider through the sequence with little thumbs popping up as you slide it.

It would be great for blurring, scanning and selecting faster without needing to step.

**Comment by peterneubauer** [comment]
related to https://github.com/mapillary/mapillary_elva/issues/658

**Comment by oscarlorentzon** [comment]
Duplicate of #171 with some additional details. Closing this one.
