### ISSUE TITLE
Filtering functionality for graph

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#192]
It should be possible to filter the graph through the public API. The format of the filter API needs to be determined. Combined filters should be supported.

For filtering to work the graph needs to handle reset, i.e. all edges should be invalidated and cleared and handling current node should be done properly elsewhere.

Different potential filters include: 
- [x] Panorama / Regular / Full panorama
- [x] User
- [x] Timespan
- [x] Sequence

Depends on the implementation of #191.

**Comment by oscarlorentzon** [comment]
I do not see a use case for existential filters for this issue. The `gpano` property, which may not be set, is also wrapped in the `pano` and `fullPano` boolean properties which encapsulates all the use cases regarding showing pano or not.

This would leave us with the following filters:

**Comparison**
`==`
`!=`
`<`
`<=`
`>`
`>=`

**Set membership**
`in`
`!in`

**Combining**
`all`

@gyllen Thoughts?

**Comment by oscarlorentzon** [comment]
The idea is that the implementation will not support nested properties so it will not be possible to filter on things like `node.latLon.lat`.

**Comment by gyllen** [comment]
@oscarlorentzon Is it a big cost to include extistential filter (if not maybe we should do it for the sake of it)

Another question we might want to ask us is if ew want the filters to map exactly to the node properties. This is a bad example but lets say we want a boundingBox filter, is that something we should think about. I don't know.

**Comment by oscarlorentzon** [comment]
Including the existential filter is not a big cost. 

What is a none node property exactly (`filters to not map exactly to the node properties`)? 
What kind of none node properties do you want to filter on? 
When would you do it?

**Comment by oscarlorentzon** [comment]
The problem with the existential filter is that the node class is wrapping all underlying properties retrieved from the API. So even if the API result would have been an object without a certain property the node will have a property with that particular name and a `has` filter would always return true. `!has` would always return false for all defined node properties.

**Comment by gyllen** [comment]
Ok I see, since we have a standard set of properties that are always set (and not dymamic as in geojson). There is no need for has filter. Skip then.

**Comment by oscarlorentzon** [comment]
The filters only apply to the spatial arrows, i.e. the sequence arrows will always be available no matter what filter is applied.
