### ISSUE TITLE
Host integration and usage examples from mapillary.github.io/mapillary-js

### ISSUE THREAD

**Issue by knikel** [mapillary/mapillary-js#198]
Currently we have a list of examples in the `README.md` which are hosted `gist.github.com` and served through `bl.ocks.org`. We should have each example as a static page on `mapillary.github.io/mapillary-js`.

Benefits of having examples built and hosted as part of this repository documentation
- examples are always running the latest `mapillary-js` version
- one place for all examples
- no external dependency
- examples are close to the actual documentation
- examples can be versioned if breaking changes happen to the APIs

**Comment by oscarlorentzon** [comment]
Done, closing.
