### ISSUE TITLE
Panorama indicator with compass

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#199]
The current panorama indicator is just a circle. An improved version of the panorama indicator could show a compass with the arrow indicating the direction with respect to north.

Needs design for visual appearance and placement.

A note is that the compass indicator could be useful for regular images too. Then the actual 360 panorama indication needs to be handled differently.

**Comment by angelday** [comment]
<img width="475" alt="screen shot 2016-12-23 at 12 36 23" src="https://cloud.githubusercontent.com/assets/50189/21453122/6eb9626c-c90c-11e6-976e-1107c958375e.png">
