### ISSUE TITLE
Breaking changes in MapillaryJS 2.0

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#202]
Issue for discussing the breaking changes in `MapillaryJS 2.0`.

### 1. Node data properties ✔️ *with changes below*

The node previously had the following data properties:
```
apiNavImIm
ca
capturedAt
fullPano
hs
image
key
latLon
loaded
loadStatus
merged
mesh
pano
sequence
user
worthy
```

Note: Here `ca`, `capturedAt`, `key`, `latLon` and `user` are duplicated through `apiNaviImIm`. 

Proposed new data properties:
```
assetesCached
alt
ca
capturedAt
focal
full
fullPano
gpano
height
image
key
latLon
loadStatus
merged
mergeCC
mergeVersion
mesh
orientation
pano
rotation
scale
sequenceKey
userKey
username
width
```

Note: `sequence` is not a public property on the node, only the `sequenceKey`.  `userKey` and `username` replaces `user` (which is the same as the new `username`).

### 2. Node edges ✔️ *with changes below*

Previously:
```
edges: IEdge[]
edgesCached: boolean
```

Proposed:
```
sequenceEdges$: Observable<IEdgeStatus>
sequenceEdgesCached: boolean
spatialEdges$: Observable<IEdgeStatus>
spatialEdgesCached: boolean
```

Note: The only way to retrieve the async edges in the proposed version is through 
two different observable streams of IEdgeStatus (`{ cached: boolean, edges: IEdge[] }`).
The async edges could potentially be set on the node prior to being set as current
node which makes events a no option.

### 3. Navigator failure cases ✔️ 

When `moveDir` or `moveCloseTo` is called with no result both methods should throw.

### 4. Marker component ✔️ 

Remove possibility to configure mapillary objects on marker component. Without that possibility the obsolete 
`VectorTilesService` and `mapillaryObjects` and related interfaces/classes (`mapillaryRect`) can be removed.

### 5. Return observables instead of promises from public viewer methods. ✖️ *discarded for this release*

Note: `subscribe` needs to be called instead of ` then`.

### 6. Remove `Rotation` edge direction type. ✔️ 

Note: Not used in library.

### 7. Component viewer options separated from general viewer options ✔️ *description below*

Make a viewer options property for all components `IViewerOptions.component` so that 
they are separated from general options and can be handled separately.

### 10. Exclude js suffix from dist files ✔️ 

Previously we published:
```
mapillary-js.min.js
mapillary-js.js
```

Proposed:
```
mapillary.min.js
mapillary.js
```

### 11. Remove deprecated `Viewer.auth` method ✔️

**Comment by gyllen** [comment]
1. This looks good to me. I think what we do miss is the original lon, lat and ca from the node. Right now we return the SfM truth.

2. Can we have a collection thats edges$ that is just all of them. Also what about timetravel edges?
What is the difference between edges and edgesCached?

3. Agree! We should then handle this in elva and show error messages (not just break silently). And urge users to report.

4. Im not sure what this means. But Im all for removing those two interfaces.

5. Not sure, Promises is a part of the standard today, very few in the javascript world is using Observables today. Maybe we can provide both options?

6. If its not used remove, I can't see a use for it outside the library either.

7. Can you give an example of how this would look?

8. 👍 

9. 👍

**Comment by oscarlorentzon** [comment]
Regarding 7: Components are just configured in a `component` property on the viewer options struct instead of directly on the viewer options struct. Makes it easier to loop through component properties only. 

Now:
```
var mly = new Mapillary.Viewer(
    'mly',
    '<your client id>',
    '<your photo id for initializing the viewer>',
    { 
        renderMode: Mapillary.RenderMode.Fill,
        baseImageSize: Mapillary.ImageSize.Size320,
        cache: true,
        keyboard: false,
        sequence: {
            maxWidth: 150,
            minWidth: 80,
        },
    }
);
```

Proposed:
```
var mly = new Mapillary.Viewer(
    'mly',
    '<your client id>',
    '<your photo id for initializing the viewer>',
    { 
        renderMode: Mapillary.RenderMode.Fill,
        baseImageSize: Mapillary.ImageSize.Size320,
        component: {
            cache: true,
            keyboard: false,
            sequence: {
                maxWidth: 150,
                minWidth: 80,
            },
        }
    }
);
```

**Comment by oscarlorentzon** [comment]
Regarding 4: Marker component cancurrently be configured to automatically show `mapillary objects` - https://github.com/mapillary/mapillary-js/blob/master/src/component/interfaces/IMarkerConfiguration.ts#L4

These objects are fetched automatically within the library when the marker component is configured for that.

From discussions around #113 the conclusion was to not fetch any `detection`, `segmentation`, `tag` (i.e. single image data in 2D) or `marker` (i.e. `lat`, `lon`, `alt` data placed in 3D) data within `MapillaryJS`. The library user need to fetch the data. `MapillaryJS` provides APIs for showing 2D and 3D data in a configurable way. 

Therefor this option and related code should be removed. Any integrations using this option needs to fetch that data on their own then.

**Comment by oscarlorentzon** [comment]
Regarding 1: `original latLon` and `original ca` are equivalent to proposed `latLon` and `ca` before SfM has been run because `cl` and `cca` are then `null` leading to duplicated data properties. When do we need the original values?

**Comment by oscarlorentzon** [comment]
Regarding 2: Time travel eges are included in the `spatial` edges category. Also, updated the original comment with types to clarify what the properties mean.

**Comment by oscarlorentzon** [comment]
Regarding 5: If we do not consider observables as a choice for the API then we need to use duplicating properties and events for the `spatialEdges$` and `sequenceEdges$` observables. Promises can not help there.

**Comment by oscarlorentzon** [comment]
Regarding 6: `EdgeDirection.Rotation` edges are not calculated when creating the graph so usage is not possible currently anyway.

**Comment by gyllen** [comment]
1. Original lon/lat is needed in elva since the tiles are based on original lonLat. We need to be able to get both of the. Right now we get it from the API struct.

2. Ok, lets not have a merged version to start with then. If user wants both they can merge themselves.

4. Agree, remove, as previously discussed no data fetching (except images and sequences) in `MJS`

5. Hmmm, Im not sure about this. Observables are not that easy to understand which will make the level to use MapillaryJS pretty high. How would a solution look like if we had both observables and signals?

6. Yes remove!

7. I like it. Im onbaord with this config. Makes sense.

**Comment by oscarlorentzon** [comment]
#### Regarding 5. Return observables instead of promises from public viewer methods:

Will implement the event based edge proposal beside the observable one and post when done.

**Comment by oscarlorentzon** [comment]
@gyllen Can you refer to the original numbers in your comment above to avoid confusion?

**Comment by gyllen** [comment]
@oscarlorentzon I did refer to the orignal ones but I think tis damn markdown autoimatically numbers them in order :/

1. 1
3. 3
7. 7

**Comment by gyllen** [comment]
Im onboard with both 1 and 5 as answered above. For 1 lets go with that whole set.

**Comment by oscarlorentzon** [comment]
#### Regarding 2. Node edges:

A proposal for the `regular properties` + `events` on top of the `observable streams` for the node edges is the following:

Properties on node:
```
sequenceEdges: IEdge[]
sequenceEdgesCached: boolean
sequenceEdges$: Observable<IEdgeStatus>

spatialEdges: IEdge[]
spatialEdgesCached: boolean
spatialEdges$: Observable<IEdgeStatus>
```
with edge status like so:
```
interface IEdgeStatus {
    cached: boolean;
    edges: IEdge[];
}
```

Then two events can be fired from the viewer class by having it subscribe to the to edges type streams and emitting whenever they change. 

```
this._sequenceEdgesSubscription = this._navigator.stateService.currentNodeExternal$
    .switchMap<IEdgeStatus>(
        (node: NewNode): Observable<IEdgeStatus> => {
            return node.sequenceEdges$;
        })
    .skip(1)
    .subscribe(
        (status: IEdgeStatus): void => {
            this._eventEmitter.fire("sequenceEdgesChanged", status);
        });

this._spatialEdgesSubscription = this._navigator.stateService.currentNodeExternal$
    .switchMap<IEdgeStatus>(
        (node: NewNode): Observable<IEdgeStatus> => {
            return node.spatialEdges$;
        })
    .skip(1)
    .subscribe(
        (status: IEdgeStatus): void => {
            this._eventEmitter.fire("spatialEdgesChanged", status);
        });
```

Library user would subscribe like so:
```
viewer.on('nodeChanged', function(node) { <store node>; });
viewer.on('sequenceEdgesChanged', function(status) { <do something>; });
viewer.on('spatialEdgesChanged', function(status) { <do something>; });
```

Edges changed events are always related to the current node. Firing events from the node class should not be regarded as an option because it requires the library user to clean up her subscriptions on every node change. The argument for keeping the edge types separated is __1)__ that they are used separately everywhere in the library and __2)__ when they are not cached upon node change they will in general be cached at different times.

@gyllen I also added __10. Exclude js suffix from dist files__.

**Comment by oscarlorentzon** [comment]
Another note regarding __2. Node edges__:

When the node is changed the library user can check the status of the two edge types through the properties:

```
interface IEdgeStatus {
    cached: boolean;
    edges: IEdge[];
}

node.sequenceEdges IEdgeStatus
node.spatialEdges: IEdgeStatus
```

Based on this fact there are two options for firing the `*edgeschanged` events. 

1. When the current node changes the respective `*edgeschanged` events are fired after the `nodechanged` event with the same info that was available from the node in the `nodechanged` event.
2. When the current node changes the first event is omitted for the repsective `*edgedchanged` events because that information was already available in the `nodechanged` event. Only subsequent changes are emitted through the `*edgeschanged` events.

The drawback of the first option is that the same information is emitted twice. 
The drawback of the second option is that to be sure to have the correct version of the respective edges both the `nodechanged` and the respective `*edgeschanged` events need to be subscribed to. 

Even though it introduces more complexity for the library user regarding subscribing to multiple events I'm opting for the second option because it only emits when information that was previously not available becomes available. Each event provides only new information.

Thoughts @gyllen?

**Comment by gyllen** [comment]
@oscarlorentzon Im leaning towards 1. since its more consistent. If you want edges you will ignore nodechange event and just perform actions there. If you just need node you will listen to nodechanged event. If you in some cases do omit the nodechange event that introduces an inconsistency in the library.

**Comment by oscarlorentzon** [comment]
@gyllen I agree on the inconsistency. Using option 1 would also make the `*edgesChanged` events behave in the same way as the `*edges$` streams which always emits after the node changes when switch mapping Let's go with option 1.

**Comment by gyllen** [comment]
@oscarlorentzon 👍

**Comment by oscarlorentzon** [comment]
All issues have been decided upon and a migration document with the conclusions is available here https://github.com/mapillary/mapillary-js/blob/3a0ab4777df0aac8ba3204583d034927fce98515/MIGRATING.md.
