### ISSUE TITLE
Migrate to TypeScript 2.0

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#206]
Handle non-nullable types and other changes in TypeScript 2.0.

**Comment by knikel** [comment]
@oscarlorentzon: Would this be a good time to introduce [`tslint-config-mapillary`](https://github.com/mapillary/tslint-config-mapillary) here too?

**Comment by oscarlorentzon** [comment]
@knikel Feels like a good time. Can we do overrides?

**Comment by knikel** [comment]
@oscarlorentzon Yes, should work with following syntax:
```
{
    "extends": "tslint-config-mapillary",
    "rules": {
        "no-errors": true,
        "no-addition": false
    }
}
```

**Comment by oscarlorentzon** [comment]
@knikel Created a separate issue for the tslint config (#215) so that it is tracked.
