### ISSUE TITLE
Clear functionality in DOMRenderer

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#21]
It should be possible for a DOMUI to clear its hash and therefore its content in the virtual DOM with an method on the DOMRenderer similar to the functionality in the GLRenderer:

https://github.com/mapillary/mapillary-js/blob/ea9e928e34d80c84ac77ff63c99aba8c2e28931b/src/render/GLRenderer.ts#L308-L310

https://github.com/mapillary/mapillary-js/blob/ea9e928e34d80c84ac77ff63c99aba8c2e28931b/src/render/GLRenderer.ts#L132-L140

DOMUIs should clear their hash (and release potential memory) on deactivation.

**Comment by gyllen** [comment]
I have a patch for this. Just missed to push.

**Comment by gyllen** [comment]
Added patch
