### ISSUE TITLE
Support panoramas as foreground plane in slider

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#210]
Currently the slider is disabled when panoramas are set as foreground. The slider is only shown for regular photos. The slider should work with panoramas as foreground plane too.

The shader bounding box handling needs to be different with a panorama because the whole image will not be in view when sliding. It should also be possible to look around while using the slider with a panorama as foreground plane forcing the slider to handle dynamic updates to the shader bounding box when panning and tilting.

This issue should only handle full panoramas.

**Comment by cbeddow** [comment]
MJS will work however if a non pano/360 is the foreground, and so will compare that one against 360s in the same location? Just not vice versa?

**Comment by oscarlorentzon** [comment]
Yes, currently it works with any image (regular or 360 pano) as background if the foreground image is a regular one. Note that in every case the images need to be connected for there to be a smooth transition.

**Comment by oscarlorentzon** [comment]
Resolved in 2.12.0.
