### ISSUE TITLE
Change tile size dynamically when level 7 tiles contain too many nodes

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#211]
When a precision 7 tile contains too many nodes the graph should automatically change tile level to precision 8 for that particular tile and continue caching in precision 8 instead. 

For level 8 the tile corresponding to the node lat lon as well as all eight neighbours need to be cached.

**Comment by gyllen** [comment]
I wonder if this is really needed, or this could be solved in another way?

**Comment by oscarlorentzon** [comment]
Not in scope. Closing.
