### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#214]
It should be possible to set a JWT bearer token to enable the library to retrieve protected resources from the API.

If the bearer token should be set in the viewer constructor it needs to be implemented in a way that does not break backward compatibility.

Within the scope of this issue is also to add `projectKey` as a property on node and retrieve from API.

**Comment by gyllen** [comment]
Also for first version this would mean that when we login we would need to recreate the whole `MJS` struct.

However I would like to know what the main hurdle with cleaning caches would be (IF we decided to be able todo this runtime)

**Comment by oscarlorentzon** [comment]
So the aim for this issue is to provide an API for setting the bearer token both in the constructor and in an auth method?

If the constructor option is not there an auth call is needed after creating the viewer which would do an unnecessary graph reset.

The auth method would be like: 

```ts
viewer.setAuthToken(token: string): Promise<Node>
```

Possible names: `auth`, `setAuth`, `setAuthToken`, `setToken` etc.

One way to add it to the constructor is as a fifth optional parameter to the `Viewer` constructor:

```ts
constructor(
    elementId: string,
    clientId: string,
    key?: string,
    viewerOptions?: IViewerOptions,
    token?: string);
```

**Comment by gyllen** [comment]
Looks good to me both function and constructor

**Comment by oscarlorentzon** [comment]
Let's aim for both function and constructor.
