### ISSUE TITLE
Add API for enabling or disabling mouse/touch handlers

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#222]
Currently the mouse and touch services (as well as the keyboard component) prevents the default behavior or when mouse events occur. There are situations when this is not preferrable, e.g. when one wants to be able to scroll past the viewer in a web page. For scenarios like this there should be a way to disable the handlers and the way they prevent the default behavior.

**Comment by oscarlorentzon** [comment]
Mouse and touch event subscriptions should also be disabled when cover is activated. This should be fixed when implementing this issue.

**Comment by gyllen** [comment]
@oscarlorentzon Awesome getting this done!
