### ISSUE TITLE
API discussion about MapillaryJS 3.0

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#223]
A list of important topics to discuss before planning for a `3.0` release.

#### 1. API return values: Promises vs Observables vs Objects vs Events
Currently we return values through promises and objects and expose events. The fact that we build on RxJS could make it hard to expose observables. If returning promises, investigate if we need a promise library or if we can make use of tslib promises.

#### 2. How to handle components
Are they part of the core library? 

#### 3. How to handle component documentation
Related to `2)`. Should they, their API and their configuration values be included in the general documentation?

#### 4. Errors
Should `MapillaryErrors` be exposed on the global `Mapillary` object.

#### 5. How to handle component states
Right now it is hard to enable the `slider` component correctly because many other components need to be disabled at the same time.

#### 6. Remove unused components
`navigation`, `image` and `background` components are examples that should be discussed.

#### 7. How to release the library
At some point we need to start generate type definitions to make it easy to use the library with typescript after installing from npm.

#### 8. Event data contracts
Currently some events emits a structure with the viewer/component set on a target property. Some events emit nothing and others emit only a simple type. All events could emit a data contract the includes a target property.

#### 9. CSS naming convention
CSS classes have different types of naming currently. Decide on a pattern and naming style and be consistent.

#### 10. Remove double click zoom functionality
The double click zoom does not play well in different ways with navigation, tag creation and marker creation. On many occasions the double click to zoom moves are unintended. We have  scroll/pinch zoom and keyboard zoom with `+` and `-` and should consider if that is enough. Double click zoom would also not play well with dynamic navigation where you click on the ground to move. 

#### 11. Build output
We should build a distribution including type definitions and main plus module files so that applications can treeshake. The types need to be dependencies in that case. Investigate what format (cjs, umd, or es5) the main files should be in and what format (es6?) the module files should be in. Build these distribution files with the TS compiler directly.

**Comment by gyllen** [comment]
1. No good anwser yet, we talked ab out this before
2. Yes I think so. Starting with other github repos will only create a dependency mess for us.
3. I think we need to rethink documentation. Maybe we should create a docbox documentation from MapillaryJS too and don't generate from code. Just a thought.
4. Not sure can we have it just as en Error object.
5. Not sure this is prio for 3.0 creating some kind of component dependency chain cna be tricky. Maybe we can think about default setups instead.
6. Yes we should make a list and remove.
7. Don't think this is prio
