### ISSUE TITLE
Bounce back for cropped panoramas

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#224]
Bounce back for cropped panoramas should behave differently from perspective images. The horizontal center points should be used for calculating vertical border distances instead of the corner points.

**Comment by angelday** [comment]
Is this because of the letterbox effect?

**Comment by oscarlorentzon** [comment]
Cropped panos are projected on a sphere in 3D space which is different from the regular images which are projected on a plane (except that we use the mesh to distort the plane). Therefore the appearance of cropped panos is different to regular images. It is unrelated to Fill/Letterbox.

**Comment by oscarlorentzon** [comment]
Cropped panorama support has been removed. Closing.
