### ISSUE TITLE
Zoom on double click

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#227]
The library should support `zoom in` on double click and `zoom out` on `SHIFT` plus double click.

How to handle `tag` and `marker` components when creating or editing will need to be investigated.

**Comment by oscarlorentzon** [comment]
Should be implemented when doing #222.

**Comment by angelday** [comment]
Is this a mapbox standard behaviour? Especially with shift.

**Comment by oscarlorentzon** [comment]
@angelday Zoom in with left double click and zoom out with shift + double click is default behavior in Mapbox GL JS and Leaflet. 

In Google Maps you zoom in with left double click and out with right double click.

**Comment by angelday** [comment]
Are we also planning to have on screen controls for this?

**Comment by oscarlorentzon** [comment]
Not at the moment but add a separate issue for that if we prefer to have that too. Would need visuals.

**Comment by oscarlorentzon** [comment]
It would be possible to disable the handler for zoom on double click when working with tagging and markers.
