### ISSUE TITLE
Naming / naming conventions for components related to UI

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#23]
Continuing the discussion started by @knikel in #19. Think it is important enough to merit its own issue.

The name UI is not really capturing the whole concept of the components that live in the UI folder.

We currently have components/classes doing essentially one of the following five things in the UI folder:

* **GL rendering** - Registers to the GLRenderer to render scenes (GLUI)
* **DOM rendering** - Registers to the DOMRenderer to render HTML elements (SimpleNavUI)
* **Displaying UI** - Creates and shows a complete UI (CoverUI)
* **Handling events** - Handles DOM events and reacts on them (KeyboardUI)
* **Intelligent actions** - Subscribes to streams and performs intelligent actions based on their combination (SimplePlayUI)

As said most of these components are not really UIs by them self. What these components do when combined together though is creating a User Experience. A GLImagePlane component, a DOMNavigation, a MouseHandler and a KeyboardHandler as well as a CacheBot and a PlayBot together creates a UX. 

With this view of things the UI folder should be renamed to UX, base classes or interfaces should be named UXComponentBase or IUXComponent respectively. 

For GL and DOM components the convention could be to prefix or suffix with GL or DOM. Handlers can be suffixed by Handler and bots by Bot. There could be five folders initially under the UX folder:

**GL**
**DOM**
**Handler**
**Bot**
**General**

**Comment by knikel** [comment]
@oscarlorentzon All valid points, I'm not 100% convinced about the `UX*` prefix yet :wink:, but I agree with everything else!

With regards to **General** components, we would call them _what they are_, right? For example current `SimplePlayUI`, will become a `SimplePlayer`?

**Comment by oscarlorentzon** [comment]
Agree on both things. Let's come up with something better than UX.

**Comment by oscarlorentzon** [comment]
Let's go with the simplest possible solution that still says something about the actual behaviour of the full collection of items. **Handlers** and **Components** are two propositions.

**Comment by gyllen** [comment]
How about *Handler*, I like Handler

@knikel @oscarlorentzon

**Comment by oscarlorentzon** [comment]
:+1: for Handler

**Comment by gyllen** [comment]
Changing this will be a pain, someone using *VB* might wanna do this :)

**Comment by oscarlorentzon** [comment]
Implemented using Component.
