### ISSUE TITLE
Certain cropped panoramas are not rendered correctly

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#230]
The following cropped panoramas are not rendered correctly:

`M85wt9fkpElneqXQLQl0Fg`
`WZpEXrJ2-t05ZWFqsfgnjQ`

**Comment by GITNE** [comment]
This looks interesting too: [```IHAXL-wJKhpIbJcSwqg2LQ```](https://www.mapillary.com/app/?pKey=IHAXL-wJKhpIbJcSwqg2LQ&focus=photo)

**Comment by oscarlorentzon** [comment]
Cropped panorama support has been removed. Closing.
