### ISSUE TITLE
Support for Z-index for tags in tag component

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#231]
The tag component needs to support Z-index to be able to render overlapping geometries properly.

Z-index could be an optional property in the Tag options struct.

**Comment by gyllen** [comment]
It could be handled simply by adding order too, first one added gets lowest z-index.

**Comment by oscarlorentzon** [comment]
The API will be clearer if we add proper support for it in the options struct. There is no extra implementation cost in adding the property. The logic for handling z-index is what will take all the implementation time.

**Comment by gyllen** [comment]
So can we add z-index support and if z-index is the same then its the adding order. Latest gets on top.

Im not sure this is super useful though. What does the z-index actually mean?

**Comment by oscarlorentzon** [comment]
Z-index will be useful. It means that the tag with highest Z-index will be rendered first, writing to the depth buffer. Subsequent overlapping tags will not render to the already rendered pixels in the depth buffer. The end result will be that every pixel will only be rendered to once even if the tags are transparent, i.e. the appearance will be that of opaque tags even if they are transparent. It will look like the tag with highest Z-index is on top of the other ones.

I would say that if tags have the same z-index the Z-index rendering behavior between them is undefined / random. If tags are not overlapping then it is no problem to have the same Z-index. 

If Z-index is used it needs to be specified correctly before added to `mjs`.

If some tags have Z-index and others do not have Z-index specified the ones without would have to be interpreted as having Z-index 0.

**Comment by gyllen** [comment]
@oscarlorentzon How is edit handled in overlapping z-indices?

**Comment by oscarlorentzon** [comment]
We do not handle z-index in tag component so it is random.

In general I think it is preferable to only edit one item at a time and the elements for editing (vertex indicators) are rendered in DOM so they will be on top regardless of how many tags have been added to the component. If enabling editing for multiple tags at the same time the behavior is undefined/random because of the fact that we do not handle it.

**Comment by gyllen** [comment]
@oscarlorentzon I think we should only handle edit for one tag at the time. So in that case the editing tag will get put on top. Other than that I think we should also have a setting that enables use of z-indexing.

**Comment by gyllen** [comment]
I think tags with same z-index should be drawn in `adding order`, just as it would be if you just painted an aera.

**Comment by oscarlorentzon** [comment]
Creating and editing tags will not be prioritized going forward.
