### ISSUE TITLE
HTML popup component and popup controls

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#237]
With the mouse event API (which supplies basic coordinates) it is now more valuable to add a popup component API.

The popup controls should:

* Automatically adjust alignment based on position on canvas (maybe if configured)
* Allow any HTML to be inserted
* Be secure
* Have a generic design
* Be anchored to a basic image coordinate
* Stick to basic coordinate position when panning/zooming

**Comment by gyllen** [comment]
@oscarlorentzon I like this requirement, lets find a use case for it first and then implement it (it might come pretty fast with tagging moving in the pipe)
