### ISSUE TITLE
Multipolygon geometry support in Tag component

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#242]
The tag component should support showing, editing and creating multipolygons. Needed for instance aware segmentations where an instance is split over multiple areas.

- [ ] Multipolygon geometry class working in perspective images
- [ ] Multipolygon geometry class working in panoramas
- [ ] Unit tests
- [ ] Create new geometries
- [ ] Edit vertices of geometries
- [ ] Add new vertices to existing geometries
- [ ] Remove vertices from existing geometries
- [ ] Fill

**Comment by mrAceT** [comment]
Looks like you did it ;)
https://bl.ocks.org/oscarlorentzon/94539cefc33296ab6f28e3a83ecdccf1
https://bl.ocks.org/oscarlorentzon/a9ad92a720d2f175c9ce7f3f982ac59f

when I place a new Mapillary.MarkerComponent.CircleMarker I use lat/lon
Is it possible to convert lat/lon to the coordinate system for a polygon?

PS: my apologies if my question should not be asked here

**Comment by oscarlorentzon** [comment]
@mrAceT Currently it is not possible.

I added an issue about creating an API method related to your question, see https://github.com/mapillary/mapillary-js/issues/296.

**Comment by mrAceT** [comment]
Great!

When it would then be possible to draw a poly**line** (with options *) feeding it lat/lon values, that would be awesome!

That way I would be able to show the path an image set follows!

*) options like width, transparency etc. When it would be possible to set a flag like use "one-point perspective" that would be perfect!

**Comment by oscarlorentzon** [comment]
Creating and editing tags will not be prioritized going forward.

Creating and rendering 3D objects (like line geometries corresponding to lng, lat values) is possible through the custom render API in v4.0.0.
