### ISSUE TITLE
moveCloseTo does not comply with applied filter

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#243]
The logic for the public `moveCloseTo` method on the viewer is carried out server side. This is a problem if a filter has been applied to the viewer because the filter will not be applied to the `moveCloseTo` call. Therefore any node, that may not comply with the filter, can be retrieved when calling `moveCloseTo`.

Do we need to handle this?
Can we send a complex combination of filters to the `moveCloseTo` API?
Should we deprecate the `viewer.moveCloseTo` method because it does not make sense in the filtered case?
Should we add a comment in the `moveCloseTo` method docs about the behavior and keep as is?

@gyllen @ptpt Thoughts?

**Comment by ptpt** [comment]
@oscarlorentzon does `moveCloseTo` call `imageCloseTo` API? Could you construct an example of the problem?

**Comment by oscarlorentzon** [comment]
Yes, it uses `imageCloseTo`.

The filter functionality in the viewer is dynamic:

https://mapillary.github.io/mapillary-js/classes/viewer.html#setfilter

Any simple property on the node can be filtered:

https://mapillary.github.io/mapillary-js/classes/node.html

A complex filter could for example be (this particular filter does not make much sense but shows the capabilities in a good way):

```
var sequenceFilter = ["==", "sequenceKey", "<my sequence key>"];
var panoFilter = ["==", "pano", "True"];
var keyFilter = ["in", "key", "<my key1>", "<my key2>", "<my key2>"];
var projectFilter = ["!in", "projectKey", "<my project key1>", "<my project key1>"];
var dateFilter = [">=", "captured_at", <timestamp>];
var orientationFilter = ["==", "orientation", 6];
var heightFilter = [">=", "width", 4096];

var combinedFilter = ["all", sequenceFilter, panoFilter, keyFilter, projectFilter, dateFilter, orientationFilter, heightFilter];

viewer.setfilter(combinedFilter);
```

A filter like this one will probably never be applied but the implementation supports it. For me this suggests that the filter should not be applied to the `imageCloseTo` call and that we should document that in some way instead.

**Comment by AbelVM** [comment]
My two cents: if you are displaying a filtered version of the coverage layer, but the viewer is not fully filtered the same way, the coherence is lost between these two elements.

![image](https://cloud.githubusercontent.com/assets/9017165/26403658/4603420c-408f-11e7-8eb1-03f72ae7700f.png)

**Comment by gyllen** [comment]
@AbelVM Nice viewer!

**Comment by oscarlorentzon** [comment]
The Viewer `move close to` functionality has been [removed in v3.0.0](https://github.com/mapillary/mapillary-js/blob/master/CHANGELOG.md#300---2020-12-10) so issue is no longer applicable.
