### ISSUE TITLE
Bug with username filter

### ISSUE THREAD

**Issue by antoinegiret** [mapillary/mapillary-js#260]
Hello,

I am using mapillary with Mapbox GL. I would like to display vector tiles containing sequences of a user in a period. After reading the documentation, I wrote those lines in my application:

```
map.addSource('mapillary', {
   type: 'vector',
   tiles: ['https://d25uarhxywzl1j.cloudfront.net/v0.1/{z}/{x}/{y}.mvt'],
   minzoom: 0,
   maxzoom: 14
});

map.addLayer({
   'id': 'mapillary',
   'type': 'line',
   'source': 'mapillary',
   'source-layer': 'mapillary-sequences',
   filter: ['all',
      ['>=', 'captured_at', startDate.getTime()],
      ['<=', 'captured_at', endDate.getTime()],
      ['==', 'username', username]
   ],
   'layout': {
      'line-cap': 'round',
      'line-join': 'round'
   },
   'paint': {
      'line-opacity': 0.6,
      'line-color': 'rgb(53, 175, 109)',
      'line-width': 2
   }
});
```
Without the filter by username, vector tiles containing sequences in a period are well displayed. Where does the problem come from? The username I used is the username displayed in the top right corner of https://www.mapillary.com/app.

Thank you by advance !

**Comment by katrinhumal** [comment]
Issue moved to [mapillary/mapillary_issues #2711](https://github.com/mapillary/mapillary_issues/issues/2711) via [**ZenHub**](https://www.zenhub.com/)
