### ISSUE TITLE
How to get link to photo page?

### ISSUE THREAD

**Issue by eugenefedoto** [mapillary/mapillary-js#263]
https://www.mapillary.com/developer/api-documentation/#retrieve-image-sources

> Attribution should include a clearly visible link to mapillary.com or to the Mapillary photo page directly.

Is there an API to get the link that I'm not noticing?

**Comment by Abbe98** [comment]
Append the image key to the following URL:
`https://www.mapillary.com/app/?focus=photo&pKey=`

Example:
`https://www.mapillary.com/app/?focus=photo&pKey=wbqWRpw1nbCQh5Hu62zoJA`

**Comment by oscarlorentzon** [comment]
Issue moved to [mapillary/mapillary_issues #2716](https://github.com/mapillary/mapillary_issues/issues/2716) via [**ZenHub**](https://www.zenhub.com/)
