### ISSUE TITLE
Can this be applied to other map types, like for the Space Station?

### ISSUE THREAD

**Issue by darenwelsh** [mapillary/mapillary-js#266]
I would love to have a way to use this "street view" as a user interface for all the imagery we have of the exterior of the International Space Station (ISS) to help plan spacewalks (ExtraVehicular Activity, or EVAs). We have a 3D model of the ISS, though I'm sure it's a lot different than how the underlying map you use for this. But would it be possible to apply this functionality to the map of ISS?

See [this repo](https://github.com/darenwelsh/EVANav) for info about the 3D ISS model we use and a project extending that to provide something like Google Nav (fastest route, etc) for background.

**Comment by oscarlorentzon** [comment]
@darenwelsh Thanks for the question. Interesting project you are working with!

MapillaryJS does not currently render 3D models, only images. You can navigate between those images based on their camera rotations and positions. We do not support fine grained navigation like what you want to do in the alternate routes example, in MapillaryJS you can only navigate from image to image.

Hope that clarifies things.

**Comment by darenwelsh** [comment]
So ... I'm not trying to ask if Mapillary can solve the route mapping. I'm wondering if there's a way to build a map of the surface of ISS (whether it is with a 3D model or some other method like how you project the Earth's surface onto a 2D plane) that can serve as a user interface wherein users can browse images taken of the surface of ISS. In Mapillary, you use a 2D map of the Earth's surface and allow users to pin photos of locations in that map. I think there must be a way to do something similar for the ISS. We have lots of photos of the hardware on the outside of ISS. I'd just like to have an easy UI where the user can move around to the location of interest and find helpful photos.

**Comment by oscarlorentzon** [comment]
Thanks for the clarification. 

With a set of densely captured images of ISS covering all angles you could use our open source Structure from Motion library [OpenSfM](https://github.com/mapillary/OpenSfM) to reconstruct the 3D scene and view the resulting sparse point cloud together with camera positions and also click each camera position to view the image taken from that position. From there you can also generate a dense point cloud of the space station. OpenSfM is the processing pipeline behind what you see in MapillaryJS. MapillaryJS is used to render the 3D reconstruction result but as mentioned the OpenSfM library contains its own lightweight viewer which should achieve what you are after.

Some OpenSfM references:

http://opensfm.readthedocs.io/en/latest/
http://opensfm.readthedocs.io/en/latest/using.html#quickstart
http://blog.mapillary.com/update/2014/11/14/opensfm.html
http://blog.mapillary.com/update/2014/12/15/sfm-preview.html
http://blog.mapillary.com/update/2016/10/31/denser-3d-point-clouds-in-opensfm.html

**Comment by oscarlorentzon** [comment]
Closing this discussion because of inactivity.
