### ISSUE TITLE
UIService compiler error

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#28]
Locally the Typescript compiler gives the following error when running `gulp ts`:

`TypeScript error: src/viewer/UIService.ts(59,35): Error TS2511: Cannot create an instance of the abstract class 'UI'.`

This is not logged when running in CircleCI.

It is still possible to run the library in the browser.

**Comment by knikel** [comment]
Thanks for catching, I will add `process.exit()` on `error`

**Comment by oscarlorentzon** [comment]
Resolved after updating node and npm to latest versions.
