### ISSUE TITLE
Unable to build mapillary with Windows

### ISSUE THREAD

**Issue by TietoaPetter** [mapillary/mapillary-js#293]
### Basic information

**MapillaryJS version**: `2.18.0`
**System/Browser**: `Windows 10`

### Steps to Reproduce Behavior

 1. Clone repo
 2. Run npm install on Windows, or use npm module from fork location

### Expected behavior
dependancies should be installed as well as a build created

### Actual behavior
the following error message appears, due to running a UNIX command in a Windows environment.
`'rm' is not recognized as an internal or external command`

### Workaround
A possible workaround or solution is to include shx into the dev dependencies by calling `npm install shx --save-dev`

then prefixing all Unix commands with shx.

`cat styles/*.css` => `shx cat styles/*.css`

also the "include all filenames" **-a** tag isn't supported with shx so  
`"copy-assets": "cp -a styles/*.svg dist",` needs to be changed to `"copy-assets": "shx cp styles/*.svg dist",`

Everything works swimmingly after that.

**Comment by oscarlorentzon** [comment]
Thanks for reporting. A Docker file has been added for platform agnostic development support.
