### ISSUE TITLE
Modal.json timeout after 15s

### ISSUE THREAD

**Issue by sstenn** [mapillary/mapillary-js#306]
Hello, when I programmatically navigate with the `Viewer - moveDir` or `Viewer - moveToKey` an AJAX call (https://a.mapillary.com/v3/model.json?client_id=...) is fired.

Sometimes this call times out and I get a bunch of error messages:
`Failed to cache spatial nodes (key)`  
`Failed to cache spatial edges (key)`  
`Failed to cache periphery bounding box`

I know it's timed out because the request is always "canceled" after 15s. In [this](https://bl.ocks.org/oscarlorentzon/317da436accbcf2ff04c642f86cefaf8) example on your [documentation](https://github.com/mapillary/mapillary-js#examples), the same thing happens when navigating.

When I open the AJAX url in another tab, it always works. I really can't tell when it get's the timeout or when it just works.

**Comment by oscarlorentzon** [comment]
The model.json API is replaced in v4.0.0. Closing this issue. Please open a new one if problems re-occur.
