### ISSUE TITLE
Better sequences in integrations examples and README + vector tiles in examples

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#31]
Lets find some better sequences and also update js to the latest version

- [x] Update README with better panorama and perspective photo keys
- [x] Update examples with better panorama and perspective photo keys
- [x] Add vector tiles to the examples

**Comment by gyllen** [comment]
`zarcRdNFZwg3FkXNcsFeGw` is a good key to start on

**Comment by knikel** [comment]
Awesome, I'll update examples after new release this week though.

**Comment by gyllen** [comment]
Can we also try to add our vector tiles to all of the examples?

**Comment by knikel** [comment]
The `README.md` has been updated. I've got all the examples work with our vector tiles. However, to make them fully functional we need to fix #57 first. After that I'll push new version of all the gists.
