### ISSUE TITLE
Correcting the angle of view is now very tedious

### ISSUE THREAD

**Issue by robhubi** [mapillary/mapillary-js#311]
### Basic information

**MapillaryJS version**: `...`
**System/Browser**: `Win 10 / Firefox 78.0.1 (64-Bit)`

### Steps to Reproduce Behavior

 1. start mapillary in browser
 2. upload a sequence of images
 3.

### Expected behavior

I very rarely correct the GPS position, it usually fits. It is different with the angle of view, which is very often severely wrong. But the correct viewing angle is often essential for orientation.

In the past (until about 2 weeks ago) a sequence was identical with an upload. But now the upload is split into numerous sequences (see picture). The many sequences in random order makes a viewing angle correction extremely tedious.

It would be helpful to have a viewing angle correction option when reviewing the upload. The image display should also work, which it rarely does at present.

### Actual behavior

The correction of the angle of view has become much more difficult.

### Additional information

![MapSequTed](https://user-images.githubusercontent.com/38103976/86541739-939a5080-bf0f-11ea-924c-3871f92b20f4.jpg)

Link to sequence 15: https://www.mapillary.com/map/im/6czgqXI1y7VV5iwLr7OB2R

**Comment by robhubi** [comment]
Step 3 forgotten: Correct the angle of view

**Comment by oscarlorentzon** [comment]
Thank you for your feedback and for reporting your problem. 

Issues reported in this repository should be specifically related to the library MapillaryJS. This issue is about a general Mapillary feature. Please submit all the information to support@mapillary.com to get support regarding your issue. Thank you.
