### ISSUE TITLE
Update/remove "Move close to latitude and longitude" example

### ISSUE THREAD

**Issue by erictheise** [mapillary/mapillary-js#317]
The [Move close to latitude and longitude](https://bl.ocks.org/oscarlorentzon/a60f3dad3f3accfe67ea1048be88df26) example makes use of `moveCloseTo()` which has been removed. The corresponding example, too, should be removed or, better, updated to reflect the new way of working.

![image](https://user-images.githubusercontent.com/317680/103931550-4e7cf400-50d5-11eb-9d79-1726e88fa7fc.png)

**Comment by oscarlorentzon** [comment]
You are correct, the example should be removed. 

From v3.0 it is required to use the [search images REST API](https://www.mapillary.com/developer/api-documentation/#search-images) for close to functionality. Based on the result on can move to an image key of choice in MapillaryJS.
