### ISSUE TITLE
FrameAnimation Rate

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#32]
Not sure this is a bug, but Im running a screen thats on 30hz, this causes my animations to be half the speed of what you probably see them in.

**Comment by oscarlorentzon** [comment]
There are a number of different ways to handle movement based on the frames and elapsed time. Examples are:

* Transitions per frame
* Transitions per second
* Meters per frame 
* Meters per second

Right now we use Transitions per frame, i.e. when the frame rate is 30 frames per second the speed is half of the speed for a frame rate of 60 frames per second.

For different situations it can even be a good idea to use different movement schemes. 

Changing to transitions per second would handle the situation with different frame rates.

**Comment by gyllen** [comment]
Yeah its a sticky situation. For now a solution would be to adjust `animationSpeed` according to FrameAnimation speed. Im not sure if you can get that speed though. But for me `animationSpeed` should be double yours. Thats way we still keep smoothness on 60hz but we keep up speed on 30hz.

**Comment by oscarlorentzon** [comment]
Exactly, **transitions per second** will handle `time delta` between frames and update animation speed accordingly.

For situations where the `time delta` between two frames is large there could be a cap on the `animationSpeed`.

**Comment by oscarlorentzon** [comment]
@gyllen Do you consider this issue as fixed after the commit below?

https://github.com/mapillary/mapillary-js/commit/8c48050cfd693eb48b99b5764fb6b80c2c5c1f6e

**Comment by gyllen** [comment]
Fixed
