### ISSUE TITLE
Mapillary client id key

### ISSUE THREAD

**Issue by sleetynine018** [mapillary/mapillary-js#330]
Hello! 
I'm using mapillary to develop an experimental web app. However I want to either hide my client id in mapillary.js on the frontend or restrict mapillary client id key to my url/ip. I checked mapillary developers documentation and mapillary.js documentation and couldn't find anything. Is that possible?
Thanks in advance

**Comment by ptpt** [comment]
Hi @sleetynine018, currently it's not possible to hide client_id on on frontend apps or restrict it.
