### ISSUE TITLE
Create PlayUI

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#34]
Add button that will be either stop symbol or plat symbol.

**Comment by knikel** [comment]
I think we should expose this as an API, I'm a bit concerned with adding another button to the viewer. The play behavior should be controlled from the outside in my opinion. E.g. as it is done on mapillary.com, from within the drawer.

WDYT?

**Comment by gyllen** [comment]
I was thinking it could be customizable at viewer initialization. UI will still have interface, but a button could be visible if user wants it. If you add button I fix rest.

**Comment by oscarlorentzon** [comment]
This has been implemented here: https://github.com/mapillary/mapillary-js/commit/a0dd4364ee0e8fd4ee21b7770abbe1e0d1c92eed

There is another issue for adding the actual button here: #68
