### ISSUE TITLE
Find way to illustrate next in sequence in DirectionsUI

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#35]
Example `pvuThYMsqOz1syYCXDaiHQ` , going real linked images will only take you that far.

However if there is a good amount of alternatives we might not wanna show sequence arrows.

**Comment by oscarlorentzon** [comment]
There should also be logic, which needs to be a little different for panoramas and perspective images, regarding when to actually show sequence arrows.

**Comment by knikel** [comment]
Agree with @oscarlorentzon. We should first decide on the behavior and then how we want to describe it.

**Comment by gyllen** [comment]
Agree this ticket is here so we make sure to add it.

**Comment by oscarlorentzon** [comment]
This issue should also handle the perspective to panorama arrow/arrows. Right now we only calculate a single panorama edge for perspective images so the focus should be that case. This behaviour could be changed to calculating multiple panorama edges in the future.

**Comment by knikel** [comment]
The `perspective->pano` arrows are added as a task in the #17. Closing this one, since we have the prev/next navigation in.
