### ISSUE TITLE
Create a Cover UI

### ISSUE THREAD

**Issue by knikel** [mapillary/mapillary-js#4]
The main purpose of this UI would be to prevent from loading unnecessary data, until activated.

**Proposition**: a container covering the whole area of the viewer, which is clickable and where clicked it initializes the viewer. Doing it that way requires finding some metaphor for activating the viewer. It's easy for platforms like YouTube or [Vimeo](https://vimeo.com/144356789) where the play button makes sense.

What action/metaphor should we use, so we don't throw unnecessary decisions at the user? Let's discuss it here.

**Comment by knikel** [comment]
@gyllen, @oscarlorentzon: I've added initial DOM structure for the CoverUI. It adds transparent overlay and a button, when the button is pressed, it removes the UI. Check [feature-cover-ui](https://github.com/mapillary/mapillary-js/tree/feature-cover-ui) branch.

The idea with this UI is to prevent other UIs from loading. Where in the app is the best place to do it in your opinion? How much this UI should _know_ about others?

**Comment by gyllen** [comment]
@knikel Looks good to me (merge it down). Next up is to figure out how to load and unload differnt uis in a clean way.

**Comment by knikel** [comment]
The initial version has been merged. Plenty to do with regards to logic, some style tweaking is still needed for touch devices.

**Comment by knikel** [comment]
Closing this, since we got `CoverUI` to a good shape. It has the custom behaviour, blur filter (when supported) and loading indication.
