### ISSUE TITLE
mapillary viewer shows black screen

### ISSUE THREAD

**Issue by hamzahaddougui** [mapillary/mapillary-js#418]
Hi Community,
I started using mapillary js and have followed instructions to use the viewer such as defining apiClient, container and imageId to initialize the viewer. Also i made calls to mapillary images endpoint and he's working as expected. But in the browser, the container that holds mapillary viewer is showing black screen. I'm using version 3.1.0 of mapillary, the latest.
![mapillary_viewer](https://user-images.githubusercontent.com/58179098/119533198-e712c880-bd85-11eb-96e3-8856f37963f2.PNG)

**Comment by oscarlorentzon** [comment]
Hi

If you are using `mapillary-js` v3.1.0, make sure that you check out the correct version of the docs. See https://github.com/mapillary/mapillary-js/tree/v3.1.0.

For v3.x you need to use `imageKey` (which is renamed to `imageId` in v4.0 see https://mapillary.github.io/mapillary-js/docs/migration/v4#renamed-1).

If you want to use MJS v4.0 beta, run `npm install --save mapillary-js@next`. Note that the documentation at https://mapillary.github.io/mapillary-js/ is about v4.x.
