### ISSUE TITLE
How to set latlng instead of mapId? 

### ISSUE THREAD

**Issue by knownasilya** [mapillary/mapillary-js#454]
### Basic information

**MapillaryJS version**: `v4`
**System/Browser**: `macos latest/chrome latest`

### Steps to Reproduce Behavior

 1. `viewer.setCenter([lat, lng])` doesn't seem to do latlng. Looks like `getPosition` returns latlng, but there is no `setPosition`.  

### Expected behavior

Expect a setPosition and latlng on init of Viewer.
Alternatively an api to find image by latlng could help be a stop gap solution, but would be slow if syncing a map to the viewer.
...

**Comment by oscarlorentzon** [comment]
There is no guarantee that an `lngLat` will have images nearby so a `setLngLat`/`setPosition` Viewer API method is not in the plans for MapillaryJS.

`setCenter` is used to set the center of the viewport for a specific image that has already been loaded in the viewer, see https://mapillary.github.io/mapillary-js/api/classes/viewer.viewer-1#setcenter.

When using a map to choose the `lngLat`, you have to query the rendered features of the coverage tiles to determine the image ID to navigate to. See https://mapillary.github.io/mapillary-js/examples/viewer-from-map, https://www.mapillary.com/developer/api-documentation, and https://blog.mapillary.com/update/2021/06/23/getting-started-with-the-new-mapillary-api-v4.html.

**Comment by knownasilya** [comment]
Thanks!
