### ISSUE TITLE
pixel coordinates to geo coordinates

### ISSUE THREAD

**Issue by sctrueew** [mapillary/mapillary-js#472]
Hi,

I have a panoramic image and a GPS point. I'd like to get [lat, long] of each pixel when the mouse moves. My program was written in C++.
I'd be appreciative of any help
Thanks in advance

**Comment by oscarlorentzon** [comment]
Please take a look at the wikipedia article on [Equirectangular projection](https://en.wikipedia.org/wiki/Equirectangular_projection) and work from there.
