### ISSUE TITLE
2x JS API moveCloseTo is stopped working

### ISSUE THREAD

**Issue by ashokvanam** [mapillary/mapillary-js#473]
### Basic information

**MapillaryJS version**: `2.20`
**System/Browser**: `Any browser`

### Steps to Reproduce Behavior

 1. moveCloseTo is not returning nodes. Instead returning into error callback methods

### Expected behavior

...

### Actual behavior

...

### Additional information

...

<img width="475" alt="mapillar_error" src="https://user-images.githubusercontent.com/3747250/137572045-9100acba-ddda-4977-a5fa-41b1f025da3b.PNG">

**Comment by oscarlorentzon** [comment]
Yes, MapillaryJS `v3.x` and lower are deprecated. Please upgrade to MapillaryJS `v4.x`, see the [migration guide](https://mapillary.github.io/mapillary-js/docs/migration/v4).
