### ISSUE TITLE
Request order change in image search

### ISSUE THREAD

**Issue by d3mon187** [mapillary/mapillary-js#488]
### Basic information

**MapillaryJS version**: `4.x`

### Feature Request

When using the image search api at graph.mapillary.com/images, a BBOX returns results at the edge of the BBOX first.  This means that since the closeTo option has been removed, you now have to request the full 2000 record set, and then calculate the center on your own.  From testing, it seems that having to return 2000 records is expensive for the user, the device, as well as Mapillary, so perhaps there could be a stipulation that BBox Center is returned first when limit=1 is set.  That would hopefully relieve some pressure on the servers and end users, and also allow the closeTo like functionality.

Thanks!

**Comment by oscarlorentzon** [comment]
The Mapillary API is independent from MapillaryJS. Please refer to the contact options at https://help.mapillary.com or https://www.mapillary.com/developer for inquiries about the API. Thank you.
