### ISSUE TITLE
Image graph module name

### ISSUE THREAD

**Issue by ClementLeBihan** [mapillary/mapillary-js#490]
Hi all,

I'm trying to add the Image Graph Window on my mapillary based webpage, but I can't find any info about it in examples sections. What is the name of this module we can see on the bottom left of the attached image ? 
![Screenshot from 2022-01-11 15-59-12](https://user-images.githubusercontent.com/12940019/148966958-2a2cb3bb-ae89-4b87-908d-778cfcaa751a.png)

Thank you by advance,
Best,
Clément

**Comment by oscarlorentzon** [comment]
Hi @ClementLeBihan

The imagery coverage layers are not a part of MapillaryJS. For coverage you can use either the Mapillary [vector tiles](https://www.mapillary.com/developer/api-documentation#vector-tiles) or [entity API](https://www.mapillary.com/developer/api-documentation#entities).

For an open source example, see the [iD editor implementation](https://github.com/openstreetmap/iD/blob/01daef345926906b28a9fcc5b9c0fb91bc128590/modules/services/mapillary.js).

**Comment by ClementLeBihan** [comment]
Alright ! 
Thank's a lot for the iD implementation link ! That's great :)
