### ISSUE TITLE
API for available photo locations

### ISSUE THREAD

**Issue by interwebjill** [mapillary/mapillary-js#521]
I have come to the mapillary-js library to find an API and sample code that supports rendering the markers and lines on a street map to indicate the location of mapillary images like in [this web app](https://www.mapillary.com/app/?mapStyle=OpenStreetMap&lat=48.886502870001976&lng=12.573790830002963&z=17&pKey=1299899683759307&focus=map&x=0.5517209813603703&y=0.5665878606950552&zoom=0.7346188884136106) and in [this article](https://help.mapillary.com/hc/en-us/articles/115001777545-Mapillary-for-ArcGIS-Online).

Is this functionality available?

**Comment by oscarlorentzon** [comment]
Yes it is, see #490.
