### ISSUE TITLE
Is it possible to view 360 images in the viewer using procedural-data-provider?

### ISSUE THREAD

**Issue by z0x00** [mapillary/mapillary-js#539]
Currently using `procedural-data-provider` to show images in mapillary js viewer. All images are 360 images, but unable to see them in a 360 degree view.

### Expected behavior

viewer should show images in 360 degree view, like in this example:
https://mapillary.github.io/mapillary-js/examples/viewer-coordinates/

### Actual behavior

currently images are appearing like in this example:
https://mapillary.github.io/mapillary-js/examples/component-tag/

**Comment by oscarlorentzon** [comment]
The code in the [spatial component](https://mapillary.github.io/mapillary-js/examples/component-spatial) and [procedural provider](https://mapillary.github.io/mapillary-js/examples/extend-procedural-data-provider) examples should get you there. 

See specifically the usage of the [`spherical`](https://github.com/mapillary/mapillary-js/blob/main/doc/src/js/utils/ProceduralDataProvider.js#L24) projection type.
