### ISSUE TITLE
Make key in initialization optional

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#58]
A couple of reasons.

1. You might not now what image you want when you initiate js
2. You might want to show initial image from a click on a map

**Comment by oscarlorentzon** [comment]
@gyllen Was this resolved here?

https://github.com/mapillary/mapillary-js/commit/63eb4efe865474b626b2f70479560b7b4a28817b

**Comment by gyllen** [comment]
@oscarlorentzon Yes
