### ISSUE TITLE
Force equirectangular images on mapillary viewer

### ISSUE THREAD

**Issue by ivensgoncalves** [mapillary/mapillary-js#595]
### Basic information

**MapillaryJS version**: `4.1.1`

### Question
I have configured the mapillary viewer instance to only start with `equirectangular` images.
But as user starts navigating the mapillary map, he/she might land in a `perspective` image at some point.
Is there any option to "hide" directions arrows heading to `perspective` images?
Or would I need to add a new type of freer camera control?

Thanks in advance.

**Comment by oscarlorentzon** [comment]
It is possible to apply a filter to ensure that only navigation arrows to certain image types are visible.

Check out the [filtering guide](https://mapillary.github.io/mapillary-js/docs/main/control#filtering) and the [camera types](https://mapillary.github.io/mapillary-js/api/interfaces/api.SpatialImageEnt#camera_type).

Specifically, use the following:

```js
viewer.setFilter(['==', 'cameraType', 'spherical']);
```

**Comment by ivensgoncalves** [comment]
@oscarlorentzon Thank you!

Sorry I've missed that from the documentation.
