### ISSUE TITLE
photo 360 filter by username

### ISSUE THREAD

**Issue by yann-insa** [mapillary/mapillary-js#606]
Hello,
 This libraory seems to be very fantastic.
 I am reaching out to inquire about a specific feature of the Mapillary API. My goal is to display images from Mapillary in my application, but I wish to filter these images so that only those uploaded by a specific user (based on their username) are shown.

I have explored your API documentation but would like to confirm if this functionality is supported. Specifically, I am interested in understanding whether the API allows filtering images by the 'creator_username' parameter and how this can be implemented effectively.

Thanks in advance

Sincerly

**Comment by oscarlorentzon** [comment]
Thanks for the interest in using MapillaryJS.

If you intend to use MapillaryJS in you application you can filter for example filter on [`creatorUsername`](https://mapillary.github.io/mapillary-js/api/classes/viewer.Image/#creatorusername) or [`creatorId`](https://mapillary.github.io/mapillary-js/api/classes/viewer.Image/#creatorid).

The [`Viewer.setFilter` documentation](https://mapillary.github.io/mapillary-js/api/classes/viewer.Viewer/#setfilter) explains how to set the filter of choice after creating the viewer.

You can try it directly in the browser in the [filtering live example](https://mapillary.github.io/mapillary-js/docs/main/control#filtering).

You can also check the [Core Functionality - Filtering](https://mapillary.github.io/mapillary-js/examples#core-functionality) example and its [source code](https://github.com/mapillary/mapillary-js/blob/main/doc/src/js/examples/viewer-filters.js).

**Comment by yann-insa** [comment]
thank a lot, i will be explore your tips
