### ISSUE TITLE
Firefox WebGL context issue

### ISSUE THREAD

**Issue by eMerzh** [mapillary/mapillary-js#64]
the viewer keep spining 
and in the console i got 
```
THREE.WebGLRenderer 73 mapillary-js.min.js:17:11773
10:07:03,954 THREE.WebGLRenderer: Error creating WebGL context. mapillary-js.min.js:17:13485

10:07:03,955 TypeError: t is null
```

in osx , firefox 44..
no issues with chrome

**Comment by knikel** [comment]
@eMerzh thanks for the feedback. I renamed your issue so we can track it better

**Comment by oscarlorentzon** [comment]
@eMerzh Do you still have problems with Firefox? Works for me in:

`Chrome 50.0.2661.86`
`Firefox 45.0.2`
`Safari 9.0.3`

**Comment by oscarlorentzon** [comment]
@eMerzh Is WebGL enabled (the `webgl.disabled` value should be false) if you go to `about:config` in Firefox?

**Comment by eMerzh** [comment]
seems ok now ... :s  
i no longer see the error

**Comment by oscarlorentzon** [comment]
Great, thanks! I'll close this then.
