### ISSUE TITLE
Slow pan on panoramas'

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary-js#66]
On the first panorama on [mapillary blog](http://blog.mapillary.com/update/2016/02/10/mapillary-js.html), there's a yellow/mustard arrow that enter into a panorama image. That image is slowly painful to pan (you have to drag a lot to move a small portion of the area).

Tested on Chrome 48.0.2564.109 on Windows 7.

**Comment by nighto** [comment]
Has this commit been deployed? It's still slow on the website.

**Comment by oscarlorentzon** [comment]
Not deployed, just commited. Will be in next release.

Works on master if you want to check it out.

Thanks for reporting.

**Comment by nighto** [comment]
Ok, I'll give it a shot. Thanks!
