### ISSUE TITLE
DOM rendered play button in PlayerComponent

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#68]
Add a setting to a visual playbutton.

- [x] Design and placement for the play button
- [x] Add PlayComponent API method and logic for setting visibility of play button. - Will not be implemented.
- [x] Add UI element with style

**Comment by angelday** [comment]
We have the following style that goes hand-in-hand with ℰ𝓁𝓋𝒶:

![screen shot 2016-05-16 at 10 29 20](https://cloud.githubusercontent.com/assets/50189/15284356/1708398a-1b51-11e6-830f-a5d7f0a4d1c4.png)

Exported the top navigation arrows as assets along with the logo:

[js_controls.zip](https://github.com/mapillary/mapillary-js/files/265817/js_controls.zip)

Let me know if you need it zeplined.

**Comment by gyllen** [comment]
@angelday @oscarlorentzon An idea, should we have a special NavigateComponent for elva, thats maybe even is a part of elva and gets loaded there? Thoughts on this?

**Comment by oscarlorentzon** [comment]
We will not make the visibility of the play button configurable for now.

**Comment by angelday** [comment]
Updated assets are posted here: https://github.com/mapillary/mapillary-js/issues/122#issuecomment-221222860
