### ISSUE TITLE
Change TypeScript definition manager from TSD to Typings

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#69]
TSD has been deprecated and Typings should be used instead.

https://github.com/DefinitelyTyped/tsd/issues/269
https://github.com/DefinitelyTyped/tsd

https://github.com/typings/typings

**Comment by waldyrious** [comment]
For future reference, this was fixed in https://github.com/mapillary/mapillary-js/compare/7d1a3c9...bf4274c
