### ISSUE TITLE
Make markers selectable

### ISSUE THREAD

**Issue by paulinus** [mapillary/mapillary-js#78]
User should be able to select a marker by clicking it on the viewer.

**Comment by oscarlorentzon** [comment]
There are a number of ways to handle selection. Two solutions come to mind for the 2.5 release.

#### OPTION 1: 

Selection handled externally based on Viewer mouse events and getMarkerIdAt if desired in application. This is possible with the API that will be exposed in 2.5.


#### OPTION 2:

Internal selection state based on clicks. Needs to handle `SHIFT` clicks and so on to select multiple markers.
Selection changed event needs to be exposed.


Related to these two options are properties on the marker options:

```
interactive property
OR
selectable + retrieveable + draggable properties
```

Setting the interactive property to true would make a marker selectable, retrievable and draggable.


#### Proposal

I propose that we go with `OPTION 1` and do not handle selection internally and also have a single interactive property for the 2.5 release. It is more dynamic for the library user but of course requires a bit more implementation work. We could still implement it in a later release.

@gyllen Thoughts?

**Comment by oscarlorentzon** [comment]
A library user can also implement hover functionality if wanted based on the Mouse + Marker API.

**Comment by gyllen** [comment]
@oscarlorentzon Agree on `OPTION 1`

**Comment by oscarlorentzon** [comment]
It is now possible to handle selection externally using the marker API together with the mouse API.
