### ISSUE TITLE
Make marker geometry configurable

### ISSUE THREAD

**Issue by paulinus** [mapillary/mapillary-js#79]
Right now markers have a predefined geometry.  There should be a way to use any geometry.

Also there should be a way to use flat icons or svg and display them on the 3D marker.

**Comment by oscarlorentzon** [comment]
@gyllen @paulinus Was this issue resolved here d7bb6c299cfe9aad0b80c7de5bc91b899a42f0cf ?

**Comment by oscarlorentzon** [comment]
For 2.5 the idea is to only support `SimpleMarker` (ice cream shaped) and `CircleMarker` (flat circle). In the future we would like to add:

`sphere`
`cuboid`
`cylinder` 
`line`
`polygon`

and 

`dynamic`

which would load a shape file with any geometry.

**Comment by oscarlorentzon** [comment]
We would also like to have markers with sprite icons.

**Comment by oscarlorentzon** [comment]
General geometries are supported through the custom render API from v4.0.0. Closing.
