### ISSUE TITLE
Speed and legend when you stop

### ISSUE THREAD

**Issue by pertile** [mapillary/mapillary-js#83]
Hi, I want to use this viewer on a blog, you can test it [here](http://ec2-54-213-245-229.us-west-2.compute.amazonaws.com/2016/03/07/pavimento-en-el-perimetro-del-barrio-jorge-newbery/).

I see 2 problems:
1) I can't get it slower, or control the time it stops on each frame, it's impossible to read a long text
2) If I stop (for reading) legend dissapears.

If I can set the speed please tell me how.

Thanks in advance.

**Comment by oscarlorentzon** [comment]
Thanks for using the library and reporting @pertile.

It is not possible to set the speed currently. As I see it, your first problem could be split in two and they are both relevant on their own.

1.a) Make it possible to set the speed of the transitions between images.
1.b) Add setting to Route component for pausing for a specified time at a specified image.

2) There could be a value in the the Route configuration specifying if the legend should disappear when the route is stopped.

**Comment by pertile** [comment]
Thanks for your answer!

If I have to put a priority a pausing would be the first one.

I think the legend must be visible by default, and optional that you could close it.

**Comment by oscarlorentzon** [comment]
The route component has been removed in MapillaryJS v4. Use the [custom render API](https://mapillary.github.io/mapillary-js/docs/extension/extend) and [popups](https://mapillary.github.io/mapillary-js/examples#popup) instead.
