### ISSUE TITLE
Legend not shown on the first frame

### ISSUE THREAD

**Issue by pertile** [mapillary/mapillary-js#84]
I made some Mapillary storytelling and the legend it's nos shown when it's on the startkey.

**Comment by oscarlorentzon** [comment]
Setting a legend on the start key should be possible.

**Comment by oscarlorentzon** [comment]
The route component has been removed in MapillaryJS v4. Use the [custom render API](https://mapillary.github.io/mapillary-js/docs/extension/extend) and [popups](https://mapillary.github.io/mapillary-js/examples#popup) instead.
