### ISSUE TITLE
Text frame 's height and position

### ISSUE THREAD

**Issue by pertile** [mapillary/mapillary-js#85]
In a storytelling, when the comment doesn't fit on a line text frame doen't get higher (is necessary this text at all?). You can test [here](http://ec2-54-213-245-229.us-west-2.compute.amazonaws.com/2016/03/07/pavimento-en-el-perimetro-del-barrio-jorge-newbery/).

I think that the text should be in the lower side, like subtitles on a movie.

**Comment by oscarlorentzon** [comment]
The height of the frame should be adjusted according to the text.

**Comment by oscarlorentzon** [comment]
The route component has been removed in MapillaryJS v4. Use the [custom render API](https://mapillary.github.io/mapillary-js/docs/extension/extend) and [popups](https://mapillary.github.io/mapillary-js/examples#popup) instead.
