### ISSUE TITLE
Coud be possibile insert clickable link in route descriptions?

### ISSUE THREAD

**Issue by cesaregerbino** [mapillary/mapillary-js#86]
Hi! I've seen that I can add plain text description in route descriptions so something like this

```
    route.configure({paths: [
    {sequenceKey: "kwAhQXNeJ16ydpMdRbfAQA", startKey: "xGp-9dDIyTKw9KIaNUr5Lw", stopKey: "UY9XCURjpN5aIq8BcR2vLA",
     infoKeys: [
         {key: "xGp-9dDIyTKw9KIaNUr5Lw", description: "Text 1 ......"},
         {key: "VPxamBh2FwysP8UH7ckxkA", description: "Text 2 ......"},
         {key: "UY9XCURjpN5aIq8BcR2vLA", description: "Text 3 ......"}
     ]
    }
    ]
```

I'd like to add some clickable link in route descriptions for example (the sintax obviously could be different  ....)

```
    route.configure({paths: [
    {sequenceKey: "kwAhQXNeJ16ydpMdRbfAQA", startKey: "xGp-9dDIyTKw9KIaNUr5Lw", stopKey: "UY9XCURjpN5aIq8BcR2vLA",
     infoKeys: [
         {key: "xGp-9dDIyTKw9KIaNUr5Lw", description: "Text 1 <a href=\"http://www.mapillary,com/\">Mapillary</a> ..."......"},
         {key: "VPxamBh2FwysP8UH7ckxkA", description: "Text 2 ......"},
         {key: "UY9XCURjpN5aIq8BcR2vLA", description: "Text 3 ......"}
     ]
    }
    ]
```

In the same way could be possibile put images, and so on ....

Is it possible now? Could be possible in a future release?

Thank a lot!

**Comment by oscarlorentzon** [comment]
Thanks for the suggestions @cesaregerbino.

It is not possible to add HTML to the route configuration at the moment, only strings.

It would be possible to change this behavior and make the configuration more powerful in a future release.

**Comment by oscarlorentzon** [comment]
The route component has been removed in MapillaryJS v4. Use the [custom render API](https://mapillary.github.io/mapillary-js/docs/extension/extend) and [popups](https://mapillary.github.io/mapillary-js/examples#popup) instead.
