### ISSUE TITLE
Add support for tiled panoramas

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#92]

**Comment by oscarlorentzon** [comment]
This is relevant for regular photos too for example when tagging.

**Comment by pbb72** [comment]
Are regular photos currently stored on the Mapillary server in their uploaded resolution, or are they all rescaled to 2048 wide and the original discarded?

**Comment by oscarlorentzon** [comment]
Related to https://github.com/mapillary/mapillary_issues/issues/518

**Comment by gyllen** [comment]
@pbb72 We have the full resolution and with tiling we plan to be able to show the full res to the user.

**Comment by pbb72** [comment]
@gyllen Yes I have noticed you keep the original res, thank you for that! :)

**Comment by oscarlorentzon** [comment]
The idea is to trigger loading the high res tiles when zooming.

**Comment by oscarlorentzon** [comment]
The idea for this is the following:

A trigger class listens to the camera position and zoom and determines the image area that needs to be loaded at a certain time. It tells a texture creator about the image area. The texture creator determines what tiles to retrieve at what zoom level to cover the area. It instructs a tile fetcher to retrieve those tiles and builds the texture when they arrive. Whenever the texture is updated it notifies an image plane render class to render the updated texture. 

```
   +--------+     +---------+     +-----------------+      +--------------+
   | Camera | --> | Trigger | --> | Texture creator | <--> | Tile fetcher |
   +--------+     +---------+     +-----------------+      +--------------+
                                           |
                                           |
                                           v
                                      +----------+
                                      | Renderer |
                                      +----------+                                                      
```
